### ISSUE TITLE
[아이템 41] Set을 마커 인터페이스로 생각하지 않는 이유

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#100]
p250 두번째 문단에서 마커 인터페이스로 생각하지 않는 이유로
add, equals, hashCode등 Collection의 메서드 몇 개의 규약을 수정했다고 했는데 뭘 수정한거지??

**Comment by pci2676** [comment]
Java8 Set에 대한 명세에서 몇가지 규약이 추가되긴 했는데  
이러한 규약을 반드시 지키면서 구현하도록 어떠한 장치가 되어있지 않고 단순히 주석으로 지키라고 명시만 되어있어

이때 말한 규약의 예는 `add(E e)`의 경우 중복되지 않은 원소만 추가 될 수 있도록 구현하는 것을 얘기하는 것 같아.

아래는 javadocs 링크와 내용의 일부분
[javadocs](https://docs.oracle.com/javase/8/docs/api/java/util/Set.html)
>The Set interface places additional stipulations, beyond those inherited from the Collection interface, on the contracts of all constructors and on the contracts of the add, equals and hashCode methods. Declarations for other inherited methods are also included here for convenience. (The specifications accompanying these declarations have been tailored to the Set interface, but they do not contain any additional stipulations.)
