### ISSUE TITLE
[아이템 42] 직렬화해야하는 함수객체가 있다면 private 정적 중첩 클래스의 인스턴스를 사용하자

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#101]
> p. 258 람다를 직렬화하는 일은 극히 삼가야한다 ~ 

직렬화 공포증이있어요
람다랑 익명클래스는 왜 다른클래스와 다르게 직렬화형태가 구현별로 다를수있어?

그리고 직렬화해야하는 함수객체를 private 정적중첩클래스의 인스턴스를 사용해서 구현하는 예제좀!

**Comment by chldbtjd2272** [comment]
jvm구현 상 람다랑 익명클래스의 직렬화 표현방식이 다를 수 있다는 내용이야
jvm의 종류가 다양한데 vm끼리 직렬화된 데이터를 전송할때 표현방식이 다르면 문제가 될 수 있겠지.

직렬화가 뭔지 잘 모르겠으면 이걸 읽어봐도 좋을거같아
> https://javarevisited.blogspot.com/2011/04/top-10-java-serialization-interview.html

**Comment by chldbtjd2272** [comment]
https://javabom.tistory.com/66
