### ISSUE TITLE
[아이템 44] removeEldestEntry

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#102]
> 263p. 여기 코드

코드에서 파라미터인 Map.Entry<K.V> eldest 를 지우면 안되는 이유가 뭐지..?
생성자에 넘기는 함수객체 얘기가 왜 갑자기 나온건가 싶어. 이 removeEldestEntry는 size()를 부를 수 있는 이유가 인스턴스 메서드라 가능하다는 점도 알았고, 그래서 생성자에서는 인스턴스가 생성이 안되어있으니까..!
근데 왠 갑자기 생성자???

**Comment by csbsjy** [comment]
나도 이부분 이해안가서 추가질문할겡
removeEldestEntry는 재정의를 위한 메서드인거야? 기본이 return false 니까 혼란와 
![image](https://user-images.githubusercontent.com/47847993/80555411-2ea41500-8a0b-11ea-8a2f-236f5ede8138.png)
내부에서 이렇게쓰던데 이거 뭐 어떻게쓰는거지 ,,? 

뒤에 나오는 불필요한 함수형인터페이스 이걸 파라미터로 대신 넘기라는거야?

**Comment by chldbtjd2272** [comment]
1.eldest는 왜 필요한가?

removeEldestEntry 재정의용 메서드로, 인터페이스상 정의된 내용은 가장 오래된 Entry를 인자로 받는 함수로 정의되어 있는거야.
이펙티브 자바에 나온 예시코드는 파라미터의 값을 안쓰고 재구현한거고 


    @Test
    @DisplayName("링크드해쉬맵에서 최유성이 아닌 가장 오래된 값은 새로운 값이 들어올때 삭제된다.")
    void name() {
        //given
        HashMap<Integer, String> testMap = new LinkedHashMap<Integer, String>() {
            @Override
            protected boolean removeEldestEntry(Map.Entry<Integer,String> eldest) {
                return !eldest.getValue().equals("최유성");
            }
        };

        testMap.put(1,"최유성");
        testMap.put(2,"이민형");
        assertThat(testMap.size()).isEqualTo(2);

        testMap.remove(1);
        assertThat(testMap.size()).isEqualTo(1);

        testMap.put(1,"박찬인");
        assertThat(testMap.size()).isEqualTo(1);
    }

이런식으로 활용할 수 도 있어

> LinkedHashMap docs
>https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html#removeEldestEntry-java.util.Map.Entry-


2. removeEldestEntry는 재정의를 위한 메서드인가?

removeEldestEntry는 재정의할 수 있도록 열어둔 메서드야
protected로 열려있는데,  LinkedHashMap에서 put에서 removeEldestEntry을 사용하고 있고

기본 구현방식에 따르면 값을 넣은 후 가장 오래된 값을 삭제할 건지를 질의하고 false를 반환해 삭제를 안하도록 구현되어있어
