### ISSUE TITLE
[아이템 43] 한정적 인스턴스 메서드함수와 비한정적 인스턴스 메서드함수

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#103]
> p.43 함수 객체가 받는 인수와 참조되는 메서드가 받는 인수가 똑같다 ~~~

두개 뭘 기준으로 한건지 글만으로 이해가안가욧
t -> then.isAfter(t) 에서 t가 isAfter인수로 들어가서 한정적인스턴스메서드함수라는건가?

**Comment by chldbtjd2272** [comment]
아니 t -> then.isAfter(t) 함수가 한정적 참조는 아니고

`
    @Test
    @DisplayName("한정적 타입 메서드")
    void name2() {
        //given
        LocalDate targetDate =LocalDate.now();
        Predicate<LocalDate> localDateUnaryOperator = targetDate.minusDays(1)::isAfter;

        assertThat(localDateUnaryOperator.test(targetDate)).isFalse();
    }
`

위 코드같이 나올 경우 한정적 타입이야
함수 인자로 받은 파라미터 타입과 targetDate.minusDays(1) 리턴타입이 같으면 저런식으로 쓸 수 있고 저런 표현이 한정적 함수타입이야.


코드를 풀어보면
`
        LocalDate minusDate = targetDate.minusDays(1);
        minusDate.isAfter(targetDate);
`
이렇게 표현되겠네
