### ISSUE TITLE
[아이템 43] 제네릭 정적 팩토리 메소드

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#104]
>pg. 260 Function.identity() 

가 정확하게 어떤건가용. 처음봤습니다....

**Comment by chldbtjd2272** [comment]
`
       /**
     * Returns a function that always returns its input argument.
     *
     * @param <T> the type of the input and output objects to the function
     * @return a function that always returns its input argument
     */
    static <T> Function<T, T> identity() {
        return t -> t;
    }
`

Function인터페이스에 있는 인자를 바로 리턴하는 함수야
