### ISSUE TITLE
[아이템 46] 블랙박스 객체

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#105]
> pg.278 축소 전략을 캡슐화한 블랙박스 객체라고 생각하기 바란다.

블랙박스 객체라는 용어는 처음 본거 같은데 간단하게 알려주면 좋을것 같아.

**Comment by csbsjy** [comment]
말그대로 블랙박스라 내부구현은 볼 수 없고(캡슐화) 클라이언트는 공개된 인터페이스를 통해서만 접근할 수 있는 객체야.  흠,, 내 생각에 꼭 "블랙박스 객체"라는 용어로 한정짓기 보다는 좀 내부를 숨긴다?는 의미를 표현할 때 흔히 사용되는 용어가 아닐까 싶어 ,,(!) ex) 블랙박스테스팅 ,,
