### ISSUE TITLE
[아이템 45] 무한 시퀀스와 지연연산

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#106]
> p.268 스트림은 데이터 원소의 유한 혹은 무한 시퀀스를 뜻한다.
...
스트림 파이프라인은 지연 평가된다.

1. 무한 시퀀스라는게 무한히 중간 연산을 늘릴수 있음을 말하는건가??
2. 지연평가라는게 중간 연산이 최종연산이 적용될때 같이 된다는걸 말한다는데 좀 더 자세히 설명해주라

**Comment by csbsjy** [comment]
1. 무한시퀀스는 말그래도 무한으로 이어지는 시퀀스를말해. 
아래 예시는 책 예시인데, 여기서 primes 메서드로 반환되는 스트림이 바로 무한시퀀스야. 2부터 다음소수를 끝도없이 반환해. 그렇기 때문에 테스트코드에서 limit을 걸어서 한정지어준거야. 
```java
 @Test
    void primesTest(){
        primes()
                .map(prime -> BigInteger.valueOf(2).pow(prime.intValueExact()).subtract(BigInteger.valueOf(1)))
                .filter(mersenne -> mersenne.isProbablePrime(50))
                .limit(20)
                .forEach(System.out::println);

    }

    static Stream<BigInteger> primes(){
        return Stream.iterate(BigInteger.valueOf(2), BigInteger::nextProbablePrime);
    }
```

2. 지연평가는 아래 코드랑 같이 보는게 더 쉬울것같아. 아래 영문은 지연평가에 대한 장점을 말해주는데, 사실 나도 제대로 해석한지는 모르겠지만 무한스트림사용 시 지연평가가 유용한 점에 대한 설명이야. 스트림은 계속해서 들어오는데 실제 사용은 종단연산이 호출될 때만 점진적으로 소모되니까 유용하다?라는 의미같은데 좀더 해석해볼게 ^__^ ; 링크를 첨부했으니 함께 해석해주면 좋겠다. 

> 스트림 파이프라인은 지연평가된다. 지연평가란 종단연산이 호출되기 전에는 중간 연산을 수행하지 않는 다는 의미이다. 
 > Lazy operations might be useful in the situations where input data is consumed gradually rather than having whole complete set of elements beforehand. For example consider the situations where an infinite stream has been created using Stream#generate(Supplier<T>) and the provided Supplier function is gradually receiving data from a remote server. In those kind of the situations server call will only be made at a terminal operation when it's needed.

https://www.logicbig.com/tutorials/core-java-tutorial/java-util-stream/lazy-evaluation.html

```java
    @DisplayName("스트림파이프라인은 지연평가된다.")
    @Test
    void stream(){
        Stream.of("2", 1, 2, "4")
                .filter((value) -> isEquals(value)) // 계속 ----- 가 출력된다
                .forEach(System.out::println); // 종단연산에 들어가니까


        Stream.of("2", 1, 2, "4")
                .filter((value) -> isEquals(value)); // 아무것도 출력되지 않는다. 종단연산이 없으니까


    }

    private boolean isEquals(Serializable value) {
        System.out.println("-------------");
        return value.getClass().equals(Integer.class);
    }
```
