### ISSUE TITLE
[아이템 45] char와 Stream

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#107]
> p.272 하지만 char 값들을 처리할 때는 스트림을 삼가는 편이 낫다.

왜..??
`chars()`는 `IntStream` 을 호출하니까 바꿔써야하는건 알겠는데 `int` 로 잘못처리 할까봐 이러는건가??

**Comment by csbsjy** [comment]
옹 그런거아닐까? 이름은 chars()인데 반환은 int니까 ,, ?

**Comment by csbsjy** [comment]
![image](https://user-images.githubusercontent.com/47847993/81258995-e8396080-9071-11ea-97c3-896de64f09d5.png)
