### ISSUE TITLE
[아이템 48] reduce 연산의 accumulator, combiner 의 규약

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#110]
>pg. 293 
accumulator와 combiner 함수는 반드시 결합 법칙을 만족하고, 간섭받지 않고, 상태를 갖지 않아야한다.

위에서 '결합 법칙'하고 '간섭받지 않는다' 는 하단 주석에 설명이 되어서 어느정도 이해되었는데
'상태를 갖지 않아야한다' 는 아직 이해가 잘 되지않는것 같아.
인스턴스의 속성인 필드 같은 것을 얘기하는거라고 생각 했는데, 맞는 생각인지 궁금합니다.

**Comment by csbsjy** [comment]
엇 나도 그렇게 생각했어, 클래스의 인스턴스 변수를 병렬스트림에서 사용하고 혹시나 변경하게되면 그 변수를 사용하는 다른 스트림은 예상할 수 없는 인스턴스 상태를 사용하게되니까!
