### ISSUE TITLE
[아이템 47] Iterable 타입추론

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#114]
> p.284 얼핏보면 Stream의 iterator 메서드에 메서드 참조를 건데면 해결 될 것 같다.

Stream안에있는 Iterator 메서드가 로타입이야? 아님 그냥 제네릭인데 타입추론을 못하는건가

**Comment by mjung1798** [comment]
근데 되게 희안하네, for문에 들어갈 때만 Iterable<String>을 모르는 건가 
아래 어댑터 코드 보니까 iterator() 메서드 리턴값 제네릭이던데

**Comment by csbsjy** [comment]
헝 나 질문제대로 이해하는지 모르계따 
![image](https://user-images.githubusercontent.com/47847993/82719613-33e14080-9ce7-11ea-9b5e-e96c146b7f84.png)

iterator 리턴타입은 Iterator고 로타입은 아니넹 
타입추론과 상관없이 for-each문은 iterable 에 한정해서 동작하는 것이기 때문에 Iterator -> iterable 로 컨버팅이 필요한게 아닌가 생각해.

**Comment by mjung1798** [comment]
iterator() 메서드가 Iteratorable을 반환하는줄 알고 반환했음.
