### ISSUE TITLE
[아이템 48] 데이터 소스가 Stream.iterate

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#115]
> p. 292 : 데이터 소스가 Stream.iterate거나 중간 연산으로 limit를 쓰면 파이프라인 병렬화로는 성능 개선을 기대할 수 없다.

limit의 이유는 알았는데, iterate의 이유는 뭐야??
아이템 45에서의 무한시퀀스? 이거때문인가

**Comment by csbsjy** [comment]
나도 그렇게 생각했어. 병렬로 수행하려면 데이터를 나눠서 스레드한테 나눠주어야하는데 무한스트림은 언제끝이날지모르고 정확히 나누는 것도 불가능하니까는

**Comment by csbsjy** [comment]
병렬 스트림은 전체 시퀀스를 청크단위로 나눠서 각각의 스레드에 전달하는 방식(Spliterator에 의해 우리가 직접 나누지 않아도됨)을 취하는데 무한스트림의 경우 청크단위로 나누는 것부터가 불가능하기 때문에 애초에 병렬로 수행 자체가 불가능해 따라서, 병렬화 자체가 안되기 때문에 성능개선 또한 일어나지 않아.
