### ISSUE TITLE
[아이템 48] Stream 명세

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#117]
> Stream 명세는 이때 사용되는 함수 객체에 관한 엄중한 규약을 정의해놨다. ~ 하지만 병렬로 수행하면 참혹한 실패로 이어지기 십상이다

이부분 뭔가 정의를 하긴 했는데ㅋㅋㅋㅋ 해도 이해가 안돼

---
내가 정리한 내용
- Stream의 reduce 연산에 건네지는 accumlator(누적기), combiner(결합기) 함수
  - 결합 법칙을(associative) 만족한다 : (a op b) op c == a op (b op c)
  - 간섭받지 않는다(non-interfering) : 파이프라인이 수행되는 동안 데이터 소스가 변경되지 않아야한다.
  - 상태를 갖지 않아야(stateless) 한다
- 출력 순서를 순차 버전처럼 정렬하고 싶으면 종단 연산 forEach 를  forEachOrdered 로 바꾸어준다.

**Comment by csbsjy** [comment]
우선 병렬로 수행하면 연산을 수행하는 순서를 보장할 수 없잖아. 그 사실을 가지고 보면,
1. 결합법칙을 만족하지 않으면 a op b op c 가 있을 때, a op b 가 먼저 수행되고 op c를 할때랑, b op c를 수행하고 a op 를 수행할 때 결과가 달라지기 때문에 병렬수행 시 문제가 될 수 있어
2. 파이프라인 수행 중 데이터 소스가 외부의 요소에 의해 변경되면 파이프라인을 수행중인 곳에서는 그 사실을 알 수 없으니까 문제가 될 수 있고,
3. https://github.com/Java-Bom/ReadingRecord/issues/110 --> 이건 나도 생각 ,,
4. 는 병렬스트림은 여러 스레드에 의해 수행되니까 연산이 언제 끝날지 모르고 출력도 마찬가지라서 말 그대로 ,,!
