### ISSUE TITLE
[아이템 49] 단언문을 사용한 유효성 검증

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#118]
> pg.300 두 번째, 런타임에 아무런 효과도, 아무런 성능 저하도 없다.

단언문을 사용한 것과 일반적인 유효성 검증의 차이점에서 왜 저 차이가 생기는지 궁금합니다.

**Comment by mjung1798** [comment]
https://docs.oracle.com/javase/8/docs/technotes/guides/language/assert.html#enable-disable

이걸 봤는데, 런타임에 실행을 안하는 듯
-ea 옵션을 안쓰면 실행에서 모두 제외되고 동작하는 것 같아.

실제로 코드 짜보니까 신기하네ㅋㅋㅋㅋ
```java
public static void main(String[] args) {
  assert false;
  System.out.println("hello!");
}
```
이런코드가 있을 때 만약 -ea 옵션없이 실행하면 AssertException 없이 그냥 hello가 출력되는데,
![image](https://user-images.githubusercontent.com/26458200/83265999-3cf97280-a1fd-11ea-9ff2-9854646d992c.png)

실행할때 vm option으로 -ea 설정하고 실행하면 AssertException이 뜬다!!
![image](https://user-images.githubusercontent.com/26458200/83266165-70d49800-a1fd-11ea-9f74-50db68536e93.png)

그래서 정말 저 말대로 런타임에 (없는 코드니까) 아무런 효과도 성능 저하도 없는거지.

**Comment by mjung1798** [comment]
추가로 -ea 옵션에 클래스 파일명 지정하면, 지정한 클래스 파일만 assert 확인한대
