### ISSUE TITLE
[아이템 52] 타입 쌍

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#119]
> p.318 2번째 문단, 어떤 방향으로도 형변환 할 수 없는 타입 쌍...

이거 뭔지 알려줄수있어??? 뭐라고 검색해야 하는지 잘 모르겠어

**Comment by mjung1798** [comment]
2번째 문단 그 문장에 [JLS, 5.1.12] 를 찾아봤는데 아래 내용이네
https://docs.oracle.com/javase/specs/jls/se7/html/jls-5.html#jls-5.1.12

> 5.1.12 Forbidden Conversions
> Any conversion that is not explicitly allowed is forbidden.

민망할 정도로 아무내용이없어라… 

사실 내생각은 그냥 두 타입이 어떤 방향으로도 형변환이 할 수 없다라고 생각을 했었는데, (애초에 TypeCast를 할 때 컴파일 에러가 나는 두 타입)
```java
class Cat{}
class Chair{}

@Test
public void test(){
  Cat cat = (Cat) new Chair;
  Chair chair = (Chair) new Cat;
}
```
이런식으로 되어있는 두 타입을 이야기 한다고 생각했었어. 좀더 찾아볼께
