### ISSUE TITLE
[아이템 53] EnumSet 정적 팩토리

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#124]
p322 enumSet 정적팩토리에서 가변인수 다중정의 패턴을 어떻게 활용하고 있는지 설명해줘

**Comment by pci2676** [comment]
![image](https://user-images.githubusercontent.com/13347548/83848958-9b68a880-a749-11ea-8250-20074016670e.png)
1개부터 5개 까지는 위와같이 오버로딩을 해서 사용하고 있고
그 이상 필요한 경우가 생길때는 아래와 같이 가변인수를 사용해서 오버로딩을 한걸 확인할 수 있네
 
![image](https://user-images.githubusercontent.com/13347548/83849041-c4893900-a749-11ea-8f22-7109909d2f84.png)

javadocs를 보면
![image](https://user-images.githubusercontent.com/13347548/83849247-1336d300-a74a-11ea-84e9-72140e556b11.png)

가변인수로 오버로딩한 메서드가 더 늦게 호출된다고 적혀있네
