### ISSUE TITLE
[아이템 54] 성능이 나빠지는 배열 할당

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#125]
> pg.325 배열을 미리 할당하면 성능이 나빠진다.

```java
return cheesesInStock.toArray(new Cheese[cheesesInStock.size()]);
```
위 코드에서 넘기는 배열을 미리 할당한다는 문맥을 내가 잘 이해를 못해서... 간단하게 알려주면 좋을것 같아

**Comment by pci2676** [comment]
재연이가 올린 [연구 결과 링크](https://shipilev.net/blog/2016/arrays-wisdom-ancients/#_conclusion)에 자세히 나와있는거 같은데
>To add insult to injury, if the collection size had changed between polling size() and calling toArray(), we are so royally screwed.
이 부분 보면 size가 불리는 순간과 toArray()이 불리는 순간에 size가 변경되면 망할수 있다는 말이 있네
