### ISSUE TITLE
[아이템 57] 반복문 관용구

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#127]
> p.346 다음은 지역변수의 범위를 최소화하는 또 다른 반복문 관용구이다.
for(int i = 0, n = expensiveComputation(); i < n; i++){
    ...
}

`expensiveComputation()`를 반복문 관용구라고 하는 것 같은데
static method를 관용구라고 말하는 건가??
반복문 관용구가 정확히 어떤 의미인지 잘 모르겠어

**Comment by Gobukgol** [comment]
저 메소드를 반복문 관용구 라고 하는 것 같진않고 저런 방식의 for문을 반복문 관용구 중 하나라고 하는 것 같아.

```java
for (int i = 0, j = 0, k = 0, l = 1; i < l ; i++) {

} // 이런식...
```
저렇게 이런 식으로 하면, 각 변수 i,j,k,l 은 저 for문 안에서만 사용할 수 있으니 지역변수의 범위를 최소화 할 수 있는 것이고,

책 예제에서 지역변수 사용을 최소화 하지 않는 방법으로는 다음과 같겠지?
![image](https://user-images.githubusercontent.com/34976178/84470878-3409a600-acbf-11ea-88f1-6faf661a037d.png)

추가로 예제 밑에 주목할 부분 예제 결과는 다음과 같아!

![image](https://user-images.githubusercontent.com/34976178/84471070-92cf1f80-acbf-11ea-8768-998de6cdc8ee.png)

![image](https://user-images.githubusercontent.com/34976178/84471109-a5495900-acbf-11ea-93fc-411c914fef10.png)
