### ISSUE TITLE
[아이템 58] for-each를 사용할 수 없는 상황 세가지

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#128]
> p.349 하지만 안타깝게도 for-each를 사용할 수 없는 상황이 세가지 존재한다.

- 파괴적인 필터링
- 변형
- 병렬 반복

위 세가지 경우 예시 코드 있으면 좋을 것 같아

**Comment by Gobukgol** [comment]
- 파괴적인 필터링
![image](https://user-images.githubusercontent.com/34976178/84472952-2b1ad380-acc3-11ea-8db7-b3d51c0fe0fd.png)
위 코드를 그대로 실행하면 
![image](https://user-images.githubusercontent.com/34976178/84472982-3e2da380-acc3-11ea-9c20-fdf3983c4773.png)
이런 식으로 Exception이 발생하고 추가로 IDE에서도 
![image](https://user-images.githubusercontent.com/34976178/84473046-5998ae80-acc3-11ea-9a37-61f2caebb0d3.png)
이런식으로 removeIf를 사용하라고 유도하고 있어
![image](https://user-images.githubusercontent.com/34976178/84473112-71703280-acc3-11ea-84bb-6b0106d971a9.png)
![image](https://user-images.githubusercontent.com/34976178/84473133-7a610400-acc3-11ea-943c-5530b3d9cc38.png)
removeIf 메소드 내부적으로 iterator를 사용해서 코드에서 명시적으로 순회를 사용하지 않게 되는 것이고.

- 변형
![image](https://user-images.githubusercontent.com/34976178/84474169-628a7f80-acc5-11ea-8a3a-d4f39f88216a.png)

![image](https://user-images.githubusercontent.com/34976178/84474318-9c5b8600-acc5-11ea-8cd8-d9ce37142e90.png)

- 병렬 반복
병렬 반복 의미가 스레드를 이용해서 동시에 처리하는 건가? 라고 생각했었는데 책 설명 밑에 코드 58-4 언급이나 스택오버플로우에도 비슷한 질문이 있어서 확인해봤는데 중첩 반복문 얘기를 하는 것 같아.

하나의 퍼블리셔에 하나의 클라이언트를 매칭하고 싶은 상황에서 for-each 문을 중첩으로 한다면 
![image](https://user-images.githubusercontent.com/34976178/84475815-24db2600-acc8-11ea-88aa-f2cab3502032.png)
모든 조합의 경우의 수가 나오니까 
반복자를 사용해서 하나씩 매칭해주는 거지
![image](https://user-images.githubusercontent.com/34976178/84475963-64a20d80-acc8-11ea-9125-fa9b99f40163.png)

![image](https://user-images.githubusercontent.com/34976178/84475992-74b9ed00-acc8-11ea-9415-469fff6c036f.png)

추가로 스택오버플로우 링크야
[https://stackoverflow.com/questions/33208013/parallel-iteration-on-multiple-collections](url)
