### ISSUE TITLE
[아이템 64] 인터페이스 대신 클래스타입을 사용해도 되는 예

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#132]
370p 에 세가지 부류가 클래스타입을 사용해도 된다고 설명하는데 해당 예제를 짜놓으면 좋을거같아

**Comment by Gobukgol** [comment]
책에 나온 예제들을 들어서 정리해서 달기

**Comment by Gobukgol** [comment]
1. 적합한 인터페이스가 없다면 당연히 클래스로 참조해야 한다.
이 예로 String을 들었는데 String의 경우 값 클래스이고 불변 객체이기 때문에 String 의 경우 final 로 상속을 불가능하게 만들었어.

![image](https://user-images.githubusercontent.com/34976178/89610997-f38d6980-d8b6-11ea-95a7-ef0772ad7ed1.png)

2. 클래스 기반으로 작성된 프레임 워크가 제공하는 객체들
OutputStream을 구현하는 클래스 중에 FileOutputStream 과 ByteArrayOutpuStream 클래스가 있는데 Oracle 문서를 보면
OutputStream에서 추가적으로 필요한 기능들을 확장해서 구현하였어.
![image](https://user-images.githubusercontent.com/34976178/89612320-7e239800-d8ba-11ea-9d94-8fcce14fa68d.png)
![image](https://user-images.githubusercontent.com/34976178/89612346-8976c380-d8ba-11ea-9649-bd643274b813.png)
[FileOutputStream oracle docs](https://docs.oracle.com/javase/7/docs/api/java/io/FileOutputStream.html)
[ByteArrayOutputStream oracle docs](https://docs.oracle.com/javase/7/docs/api/java/io/ByteArrayOutputStream.html)
따라서 확장한 기능들을 사용하기 위해선 클래스를 참조해야겠지. 그리고 java.io의 OutputStream 관련한 객체들을 구현한 것을 데코레이터 패턴이라고 한대.

3. 인터페이스에는 없는 특별한 메소드들을 제공하는 클래스
PriorityQueue 클래스의 경우 Queue 인터페이스에는 없는 자신의 Comparator를 반환하는 Comparator 메소드를 제공해.
![image](https://user-images.githubusercontent.com/34976178/89612697-6698df00-d8bb-11ea-8557-571c4b7c0e13.png)
