### ISSUE TITLE
[아이템 67] jmh

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#133]
자바 코드의 상세한 성능을 알기 쉽게 보여주는 JMH라는 설명이나오는데,
간단한 사용법과 사용예제를 만들어서 보여줘

**Comment by Gobukgol** [comment]
```groovy
plugins {
    id "me.champeau.gradle.jmh" version "0.5.0"
}
dependencies {
    jmh 'org.openjdk.jmh:jmh-core:0.9'
    jmh 'org.openjdk.jmh:jmh-generator-annprocess:0.9'
}

wrapper {
    gradleVersion = '5.5'
}
```
build.gradle 이야. gradle 버전 명시적으로 준 것은 5.5 이하 버전에서 gradle 빌드할때 오류가 있다고 나오더라고, 그래서 5.5로 주니까 잘 실행되었어.

다음으로 패키지 구조인데, 다음과 같이 패키지 구조를 잡으라고 해서 
![image](https://user-images.githubusercontent.com/34976178/84530819-7dd5a900-ad1e-11ea-8fee-f69d4ad2ef45.png)

추가로 jmh 생성해서 예제를 구현했어
![image](https://user-images.githubusercontent.com/34976178/84530877-99d94a80-ad1e-11ea-813c-3c20b824f240.png)

다음은 실제 테스트 해볼 클래스야, 0부터 10000사이의 값을 더하는데 한 메소드는 for문 다른 메소드는 IntStream의 sum() 메소드를 이용했어

```java
@State(Scope.Thread) //쓰레드별로 인스턴스 생성
public class SumLoopBenchmark {

    @Benchmark
    @BenchmarkMode(Mode.Throughput) // 작업에 걸리는 총 시간
    @OutputTimeUnit(TimeUnit.SECONDS) // 측정에 사용할 시간 단위
    public void sumForLoop(Blackhole blackhole) {
        long sum = 0l;

        for (int i = 0 ; i < 10000 ; i++) {
            sum += i;
        }

        blackhole.consume(sum); // 계산 결과값을 따로 반환하거나 소비하지 않으면 무시될 수 있기때문에 해당 메소드를 통해 소비
    }

    @Benchmark
    @BenchmarkMode(Mode.Throughput)
    @OutputTimeUnit(TimeUnit.SECONDS)
    public void sumIntStream(Blackhole blackhole) {
        long sum = IntStream.range(0, 10000)
                .sum();

        blackhole.consume(sum);
    }
}

```
```java
public class BenchmarkMain {
    public static void main(String[] args) throws RunnerException {
        Options options = new OptionsBuilder()
                .include(BenchmarkMain.class.getSimpleName())
                .forks(1)
                .build();

        new Runner(options).run();
    }
}
```
메인 메소드에서 실행하면...
![image](https://user-images.githubusercontent.com/34976178/84531766-06087e00-ad20-11ea-88ff-3588dad64ba7.png)

각 메소드에 대해 워밍업 5번, 실제 계산 5번의 작업을 5번 진행해.

for 문
![image](https://user-images.githubusercontent.com/34976178/84531845-2b958780-ad20-11ea-8b5f-59f82f97bbc8.png)

IntStream
![image](https://user-images.githubusercontent.com/34976178/84531862-3223ff00-ad20-11ea-9d7d-615f311bfe61.png)

총 결과 
![image](https://user-images.githubusercontent.com/34976178/84531895-3ea85780-ad20-11ea-9796-c98ae8b3a110.png)

**Comment by Gobukgol** [comment]
[블로그 작성 글 링크](https://javabom.tistory.com/75)
