### ISSUE TITLE
[아이템 76] 실패원자성과 스레드

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#137]
> p.408, 실패원자성은 일반적으로 권장되는 덕목이지만 ,,~ 

ConcurrentModificationException을 잡았을 때도 왜 객체는 사용할 수 없는지? 그리고 Error는 왜 복구할수 없는지?

**Comment by chldbtjd2272** [comment]
실패원자성을 얻는 방법은 모두 공통적으로 객체의 상태를 바꾸기 전에 예외들을 잡아낼 수 있어

근데 일반적으로 ConcurrentModificationException은 두개의 스레드가 접근해 값을 동시에 바꾸고 나서야 예외가 발생했다는걸 알 수 있기 때문에 이미 예전 상태로 돌아가기 힘들다는 거지

또 Error는 java에서 발생하면 심각한 손상이라 판단하여 프로세스를 그냥 종료시키기 때문에 복구할수없어
