### ISSUE TITLE
[아이템 72] 예외와 직렬화 사이의 관계성

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#138]
> p. 398 단 예외는 직렬화할 수 있다는 사실을 기억하다 (직렬화에는 많은 부담이 따르니)

그렇다면 표준예외에서는 직렬화에 대한 처리가 이미 되어있다는 맥락이야? 아니면 확장했을때 직렬화에 대한 어떤 부담이 있다는 건가?
표준 예외와 직접 만든 예외를 직렬화 + 역직렬화 했을 때 어떤 결과가 나는지 궁금해

**Comment by chldbtjd2272** [comment]
맞아 표준예외들은 이미 직렬화가 다 구현되어있어 
Throwable 클래스에서 직렬화를 구현하고 있고, 각 표준예외들은 고유 시리얼넘버들을 들고있지

표준예외들을 직렬화하는것보다 내가 구현한 클래스를 직렬화+역직렬화 했을때 부담이 되는건 내가 만든 예외는 표준이 아니기 때문이겠지.
직렬화가 부담되는 이유는 작은 변화에도 오류를 발생시킬 수 있다는거야, 내가 만든 예외에 정확한 스펙을 상대측이 알아야 한다는 의미고,

표준예외들은 그럴 필요가 없겠지, 자바의 기본 표준으로 다 똑같이 맞춰져 있을테니까
