### ISSUE TITLE
[아이템 79] 정적 필드를 동기화할 떄 주의점

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#139]
> p.426, 마지막문단. 여러 스레드가 호출할 가능성이 있는~

질문 : 한 다섯번 읽어봤는데 이해가 안가요 함께 고민해보아요

**Comment by mjung1798** [comment]
여러 스레드에서 모두가 한 정적변수의 락을 갖고있고, 동시에 수정이 가능하다는게, 여러개의 스레드가 한개의 정적변수값을 똑같이 바라보고있다는거구.
그러다보니 N개의 스레드가 1개의 정적변수를 접근하고 이용하고 그래서 전역변수처럼 쓰인다? 이렇게 이해했음.
안그래도 클래스 변수라서 모든 클래스가 공통적으로 쓰는데 동기화까지 걸어서 모든 쓰레드도 공통적으로 사용한다?

**Comment by csbsjy** [comment]
클라이언트가 여러 스레드로 복제돼면 동기화를 해도 소용이없다는 뜻인거같은데 이해가안되네 ㅠ 외부에서 동기화할 방법이 없다 ---> 이 말이 좀어려운거같앙
