### ISSUE TITLE
[아이템 78] AtomicLong

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#140]
> p.418 AtomicLong을 사용해보자. .... 이 패키지에는 락 없이도 스레드 안전한 프로그래밍을 지원하는 클래스들이 담겨있다.

질문 : AtomicLong이 락 없이도 스레드 세이프한 프로그래밍을 지원한다는데, 그럼 AtomicLong은 내부에서 Synchronized 키워드는 안쓰는것 같은데 어떤식으로 스레드 세이프를 보장하는지 간단하게 알려줘!

**Comment by csbsjy** [comment]
-- 네이티브 코드여서 찾아보기 쉽지않다 --
