### ISSUE TITLE
[아이템 79] 동기화 기법

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#141]
> p.426 락 분할, 락 스트라이핑, 비차단 동시성 제어

질문 : 동기화 기법의 3가지에 대한 각각의 예시를 보고싶어

**Comment by csbsjy** [comment]
코드는 추가할겡

- 락 분할(lock splitting) - 하나의 클래스에서 기능적으로 락을 분리해서 사용하는 것(두개 이상의 락 - ex: 읽기전용 락, 쓰기전용 락)
- 락 스트라이핑(lock striping) - 자료구조 관점에서 한 자료구조 전체가 아닌 일부분(buckets or stripes 단위)에 락을 적용하는 것
- 비차단 동시성 제어(nonblocking concurrency control)  - BlockingQueue 같은건가 ,,

**Comment by csbsjy** [comment]
**락 스트라이핑**
구조적으로 하나의 자료구조를 나눠서 라킹하는 방식(아래 이미지 참고)
![image](https://user-images.githubusercontent.com/47847993/86598861-b9d7f300-bfd8-11ea-89b2-69896f9ecd69.png)

ConcurrentHashMap 이 가장 대표적인 예여서 해당 부분 첨부할게!

```java
private static final int DEFAULT_CONCURRENCY_LEVEL = 16;
```

ConcurrentHashMap 의 위 필드가 Lock Segment(라킹하는 부분의 갯수)를 의미하고, 이건 우리가 생성자로 조정도 가능해.

```java
 for (Node<K,V>[] tab = table;;) {
            Node<K,V> f; int n, i, fh; K fk; V fv;
            if (tab == null || (n = tab.length) == 0)
                tab = initTable();
            else if ((f = tabAt(tab, i = (n - 1) & hash)) == null) {
                if (casTabAt(tab, i, null, new Node<K,V>(hash, key, value)))
                    break;                   // no lock when adding to empty bin
            }
            else if ((fh = f.hash) == MOVED)
                tab = helpTransfer(tab, f);
            else if (onlyIfAbsent && fh == hash &&  // check first node
                     ((fk = f.key) == key || fk != null && key.equals(fk)) &&
                     (fv = f.val) != null)
                return fv;
            else {
                V oldVal = null;
                synchronized (f) {
``` 

이건 putVal 메서드의 일부분인데 synchronized 로 감싼 f 라는 락을 위에서 계속 계산하는거를 확인할 수 있어. 코드까봐도 이해 안돼서 잘 모르겠지만 찾아보니까 해쉬값 이용하는듯 ,,? 

출처) https://www.netjstech.com/2016/05/lock-striping-in-java-concurrency.html

**Comment by csbsjy** [comment]
**락 분할**
간단하게 기능별로 락을 나누는 사용법이야

```java
public class JavabomCollection {
    private static final Object READ_LOCK = new Object();
    private static final Object WRITE_LOCK = new Object();
    private final Map<Long, String> data;

    public JavabomCollection(final Map<Long, String> data) {
        this.data = data;
    }

    public void putData(final Long id, final String contents){
        synchronized (WRITE_LOCK){
            this.data.put(id, contents);
        }
    }

    public String getData(final Long id){
        synchronized (READ_LOCK){
            return this.data.get(id);
        }
    }
}
```

**Comment by csbsjy** [comment]
마지막거는 뭘까 ,, 차단하지않고 동시성을 제어한다 ,, 락을 안쓰는걸까 ,,?

**Comment by mjung1798** [comment]
https://homoefficio.github.io/2017/02/19/Blocking-NonBlocking-Synchronous-Asynchronous/
