### ISSUE TITLE
[아이템 78] 동기화에서 통신과 자바메모리 모델의 관계

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#142]
> p.415 이는 한 스레드가 만든 변화가 다른 스레드에게 언제 어떻게 보이는지를 규정한 자바의메모리 모델 때문이다

질문 : 자바의 메모리 모델과 상관관계가 궁금해. 여기에 링크 연결되어있는데 링크 내용도 첨부부탁해여

**Comment by csbsjy** [comment]
어후 링크는 잘 안읽힌다 ㅋㅋㅋㅋ  
https://docs.oracle.com/javase/specs/jls/se8/html/jls-17.html 여기 17.4 인데 헝 뭐부터 읽을지모르겠다 

우선 여기서 나오는 자바의 메모리 모델은
![image](https://user-images.githubusercontent.com/47847993/86458658-8f7c0080-bd60-11ea-8884-6a3cdc6b0632.png)

스레드가 변수를 읽어올 때 CPU Cache 에서 읽어오게 돼. 그래서 실제 변수의 값이 변화해도 해당 스레드는 그 전에 읽었던 CPU Cache 에서 읽기 때문에 변경된 사항을 볼 수 없는거야. volatile 키워드를 붙이면 해당 변수를 읽어올 때 메모리에서 직접 읽어오게 되는데 그렇기 때문에 안정적인 통신은 보장할 수 있어.(하지만 뒤에 ++ 연산에 대한 원자성, 배타적 수행을 보장할 수는 없공 ,,)

**Comment by csbsjy** [comment]
![image](https://user-images.githubusercontent.com/47847993/86505057-272e2d00-bdfb-11ea-82c1-6f1b3b90e006.png)

논의 한번 해보구시픔 ,,

**Comment by csbsjy** [comment]
CPU 안에 여러 코어, 그리고 코어에서 스레드가 나눠진다.
