### ISSUE TITLE
[아이템 78] 안전 발행

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#143]
> p.419 객체를 안전하게 발행하는 방법은 많다. 클래스 초기화 과정에서 객체를 정적필드, volatile필드, final 필드, 혹은 보통의 락을 통해 접근하는 필드에 저장해도 된다.

질문 : 다른건 이해가 가는데 정적필드는 왜 안전한거야..???

**Comment by csbsjy** [comment]
아 정적필드로 발행하는게 안전하다는게아니구 공유하는 부분만 동기화한 필드를 다른 스레드와 공유하는 방식 중 하나가 정적필드라는 말인거같아! 정적필드가 곧 안전발행이라는 의미는 아닌거같아!

**Comment by csbsjy** [comment]
헉 아닌가보다 잠만
