### ISSUE TITLE
[아이템 81] 허위각성

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#145]
> p.[436] 조건이 만족되지 않아도 스레드가 깨어날 수 있는 상황,,

질문 :  조건이 만족되지 않아도 스레드가 깨어날 수 있는 상황에서 허위각성이라는 현상이 있는데, 해당 현상이 뭔지 설명해줘

**Comment by pci2676** [comment]
위키 참고! https://en.wikipedia.org/wiki/Spurious_wakeup
