### ISSUE TITLE
[아이템 82] synchronizedMap이 반환한 맵의 컬렉션 뷰를 순회할 때

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#147]
> p. 440, 추가 설명부분

질문 : synchronizedMap을 반환한 맵의 컬렉션 뷰를 순회할 때(keySet()) keySet으로 나온 Set이 아닌 Map을 동기화하지 않으면 동작을 예측할 수 없다고하는데, 그 예시를 보여주면 좋을 것 같아

**Comment by mjung1798** [comment]
이런 코드를 짜봤어 1번 쓰레드에서는 map에 락을 걸어서 현재 Map에 있는 원소들을 계속해서 조회하는 코드,
2번 쓰레드에서는 락이 걸려있는 map에 put을 하는 코드.

만약 set을 락으로 걸게되는 경우에는,
synchronizedMap 에의해서 new SynchronizedMap 객체가 생성되게 된 상태이고
map은 내부적으로 여기있는 mutex 변수로 관리가 되는상황이야.
그리고, set이 생성될 때도 마찬가지로 new SynchronizedSet 객체가 생성되게 되는데 락이 이 객체에 걸리게 되는 것같아.

그래서 set에 락을 걸었으니 map에 락이 걸려있지 않으니까, 아래 코드처럼 다른 쓰레드에서 map에 put 명령을 했을 때, ConcurrentModificationException 이 터지게 돼!

프로그래머는 map에서 파생된 set에 락을 걸었으니 map도 같이 락이 되겠지라고 생각할 수 있으나 
실제적으로 keySet할때 새로운 객체가 생성되서 오판이었던 것이지



```java
@Test
    void testMap() {

        Map<String, String> map = Collections.synchronizedMap(new HashMap<>());
        Set<String> set = map.keySet();

        map.put("1", "test");
        map.put("2", "test");
        map.put("3", "test");
        map.put("4", "test");

        new Thread(() -> {
            synchronized (set) {
                while(true){
                    for (String key : set) {
                        System.out.print(key);
                    }
                    System.out.println();
                }
            }
        }).start();

        new Thread(() -> {
            map.put("0", "test");
        }).start();

    }
```

**Comment by chldbtjd2272** [comment]
이거 코드볼때는 map과 set은 같은 락객체를 공유하고 있는데 set의 iterator에는 락을 안걸고 있어서 클라이언트에서 동기화를 해줘야하는 거 같고, 사용자가 동기화때 map과 set이 동시에 접근할 수 있는 table을 수정할 수 있는 인터페이스는 map이라 map을 동기화해야하는거 같아

**Comment by mjung1798** [comment]
for 문이 내부 동기화가 되어있지않고,
set은 값을 넣는게 아니라, 값을 보기만 하는 것이라서 동기화를 걸었을 때 의미가 없다.
여기서 동기화가 의미가 있으려면 만들어져있는 map에 새로운 값을 추가하려고 하는 것인데, set에서는 애초에 그런 동작이 되지 않는다.
따라서 새로운 값 을 추가하려고 하는 map에 synchronized를 걸어주는게 맞다.
