### ISSUE TITLE
[아이템 83] 초기화 순환성

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#150]
> p.443 지연 초기화가 초기화 순환성을 깨뜨릴 것 같으면 `synchronized`를 단 접근자를 사용하자.

질문 : 초기화 순환성이 뭔지 몰라서 찾아보니까 [이 글](https://stackoverflow.com/questions/1941572/circularity-in-class-initialization)에서 
A 생성자가 B생성자를 부르고 B생성자가 A생성자를 불러서 무한 사이클이 생기는것 같은 상황을 말하는 것 같은데 
`초기화 순환성을 깨뜨릴 것 같으면` 이 문장이 이해가 안되네..! 
초기화 순환성이 깨진다는것 순환 사이클이 깨진다는 것 아닌가? 내가 잘못 이해하고 있는것 같아서!

아래 예제(83-2)가 초기화 순환성과 무슨 관계인지도 잘 모르겠어!
```java
private FieldType field;

private synchronized FieldType getField(){
    if(field == null) {
        field = computeFieldValue();
    }
    return field;
}
```

**Comment by mjung1798** [comment]
음 문맥 이해 안된거는 번역 문제 같기도? 원서 내용에 따르면 오히려  "지연초기화를 순환성을 깨는데 사용하고 싶다면!" 으로 해석이 되네
> If you use lazy initialization to break an initialization circularity, use a synchronized accessor because it is the simplest, clearest alternative:

**Comment by mjung1798** [comment]
순환 초기화: 클래스가 로딩되는 순서에 따라, 초기화 순서가 불명확함. 
https://github.com/Java-Bom/ReadingRecord/issues/155 (자바의 클래스 초기화 순서 관련 링크)

**Comment by mjung1798** [comment]
[초기화 순환성]
클래스가 로딩되는 순서에 따라 초기화 순서가 불명확하기 때문에, class A에서 멤버변수의 위치가 달라지면, sout 결과값도 달라짐
즉, 초기화 순서에 대해 프로그래머의 생각대로 이루어지지 않음.

```java
static class A{
        static int number = 1;
        static int number2 = B.number;
    }

    static class B{
        static int number = A.number;
    }

    public static void main(String[] args) {
        System.out.println(A.number2); // 1
    }
```
```java
class CircularityTest {

    static class A{
        static int number2 = B.number;
        static int number = 1;
    }

    static class B{
        static int number = A.number;
    }

    public static void main(String[] args) {
        System.out.println(A.number2); // 0
    }

}
```
```

**Comment by mjung1798** [comment]
결론..? : 현재 순환 참조로 인해 클래스 변수 참조 순서가 불명확 한데
책의 내용에 따르면 synchronized 지연초기화를 사용할 경우엔 이런 문제를 없앨 수 있다.
