### ISSUE TITLE
[아이템 83] 코드 83-4 지역변수 성능 향상

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#151]
> p.444 특히 result라는 지역변수가 필요한 이유는 뭘까?

질문 : 예제 코드(83-4)에서 첫번째 if 블럭에서 그냥 `field == null` 검사하는거랑 어떤차이가 있는거지?
왜 성능이 더 나아지는지 모르겠어

**Comment by mjung1798** [comment]
책에 따르면 필드를 딱 한번만 읽어주기 때문에 성능이 높아진다고 했는데,
만약 오빠 말대로 field == null 검사를 하게 된다면
```java
if (field != null) { // 첫번째 검사(락 사용안함)
            return field;
        }
```
이런식으로 코딩을 하게 될테고 이때 field변수를 두 번 참조를 하게 돼.
음, thread1번에서 이미 초기화가 되어있어서 field!=null을 검사하려고 했는데,
다른 thread 2, 3, 4, 5 번은 초기화가 된 변수에 대해 아직 스레드간 통신이 되어있지 않아서 synchronized 블록을 타게 된다면 이 field 변수는 lock이 될꺼고
thread 1번은 해당 field 변수가 lock이 풀릴때까지 기다려야 할꺼야! 
근데 그과정이 ```field == null```을 이용한 코드에서는 2번을 거쳐서 lock을 기다려야하는 반면에 위처럼 지역변수를 사용하게 되면 1번을 거치기 때문에 더 성능이 높다고 이해를 했음.
