### ISSUE TITLE
[아이템 82] 상속용 클래스 인스턴스의 락사용

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#153]
> p.441 상속용 클래스에서 자신의 인스턴스를 락으로 사용한다면 하위 클래스는 아주 쉽게, 그리고 의도치 않게 기반 클래스의 동작을 방해할 수 있다.

이부분 예제있으면 좋을것 같아!
또 개인적으로 궁금한건데 이 부분이 우리 하위 클래스에서 오버라이드된 메소드를 상위 클래스가 호출할때 문제가 됐던 것과 같은 문제일까?

**Comment by mjung1798** [comment]
https://github.com/Java-Bom/ReadingRecord/issues/149 에 적어두겠음!
