### ISSUE TITLE
[아이템 83] 이중검사 관용구의 지역변수

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#154]
> p.444 코드 83-4 예제 코드, result 지역변수가 필요한 이유
```java
private volatile FieldType field;

private FieldType getField() {
    FiledType result = field;
//생략...
}
```

여기에서 result 지역변수가 필요한 이유를 필드가 이미 초기화된 상황에서 그 필드를 딱 한 번만 읽도록 보장하는 역할을 한다.

라고 하는데, 이부분을 정확하게 이해를 잘못하고 있어서! 예전에 비슷한 얘기했던것 같긴한데 기억도 잘안나고...

**Comment by mjung1798** [comment]
https://github.com/Java-Bom/ReadingRecord/issues/151
