### ISSUE TITLE
[아이템 85] 객체 역직렬화 필터링

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#156]
> p.453 직렬화를 피할 수 없고 역직렬화한 데이터가 안전한지 완전히 확신할 수 없다면 객체 역직렬화 필터링(java.io.ObjectInputFilter)을 사용하자. 
> p.454 필터링 기능은 메모리를 과하게 사용하거나 객체 그래프가 너무 깊어지는 사태로부터도 보호해준다. 하지만 앞서 보여준 직렬화 폭탄은 걸러내지 못한다.

질문 : 역직렬화 필터링으로 블랙리스트 화이트리스트 등록 방식이 궁금합니다. 그리고 
객체그래프가 깊어지는 사태는 A.class->B.class->C.class->D.class 이런식으로 객체가 객체를 참조하는 방식이구 직렬화 폭탄은 위에 HashSet 예제 따면 A->A*2->A*4 와 같은 형식으로 늘어난다고 이해해했는데 맞나여?

**Comment by Gobukgol** [comment]
직렬화를 많이 사용안해봐서 코드가 조금 지저분한데...  먼저 블랙리스트 화이트리스트 등록 방식부터 볼께.
먼저 블랙리스트는 특정 객체들을 지정해서 해당하는 객체들을 막는 방식이라면, 화이트리스트는 반대로 허용하는 객체들을 제외하곤 전부 막는 방식이고 이것을 역직렬화 필터링으로 구현해봤어

![image](https://user-images.githubusercontent.com/34976178/88313161-1152be80-cd4e-11ea-8784-f82e9465f7b5.png)
필터링 대상 클래스들의 패키지 구조야.

먼저 화이트리스트 방식을 볼께

![image](https://user-images.githubusercontent.com/34976178/88313568-aeadf280-cd4e-11ea-94a2-c1f77f7b9724.png)

명시한 패키지의 클래스라면 역직렬화를 허용하고 아니면 전부 거부하는 filter야

```java
ObjectInputStream stream = new ObjectInputStream();
stream.setObjectInputFilter(filter) //filter 등록
```

![image](https://user-images.githubusercontent.com/34976178/88313491-950cab00-cd4e-11ea-9544-415be914ab8d.png)

위의 assert 문을 보면 Accept 클래스의 경우 exception throw 없이 역직렬화가 정상적으로 진행되지만,
Reject 클래스나 Unknown 클래스의 경우 InvalidClassException을 throw 해.

이와 반대로 블랙리스트 방식은

![image](https://user-images.githubusercontent.com/34976178/88313741-eae15300-cd4e-11ea-949d-06345aa3cb96.png)

명시한 패키지의 클래스라면 역직렬화를 거부하고 아니면 전부 허용하는 filter야.

![image](https://user-images.githubusercontent.com/34976178/88313897-211ed280-cd4f-11ea-9964-60fed3f1cf8b.png)

위의 assert 문을 보면 화이트리스트 방식과 다른 점이 보이는데 마지막 Unknown 클래스의 역직렬화를 허용해. 그래서 의도치않게 역직렬화를 허용하는 경우가 생겨.

--------------------------------------------------------

너가 이해한게 맞는것 같아! 객체 그래프에 대해서 필터링하는 방법을 간단하게 구현해봤어.

![image](https://user-images.githubusercontent.com/34976178/88314382-cf2a7c80-cd4f-11ea-8ec0-81dbefbf81cf.png)

이런식으로 객체 그래프 깊이가 최대 4까지 내려갈 때.

![image](https://user-images.githubusercontent.com/34976178/88314468-ef5a3b80-cd4f-11ea-88e3-96f36a6a795a.png)

만약 현재 역직렬화하려는 객체의 깊이가 3보다 크다면 역직렬화를 거부하는 필터링이야.

![image](https://user-images.githubusercontent.com/34976178/88314588-1d3f8000-cd50-11ea-9ee9-65ab296e088e.png)

그 결과 A 클래스를 직렬화하면 D 클래스까지 내려갔을때 깊이가 3보다 커져서 InvalidClassExcetpion을 던지고,
B 클래스의 경우 D 클래스까지 내려가더라도 깊이가 3이니 정상적으로 역직렬화가 진행돼!

지금까지의 코드들은 이 블로그를 참고해서 구현했어. [Blog](https://countryxide.tistory.com/90)

**Comment by pci2676** [comment]
클래스 멤버변수로 배열을 들고 있을 때 배열의 원소도 하나의 depth로 체크를 하는지 알아봐줘
HashSet 예제로!

**Comment by Gobukgol** [comment]
```java
static class D implements Serializable {
        public String d = "world";
    }

    static class E implements Serializable {
        public F[] arrays = {new F()};
    }

    static class F implements Serializable {
        public D d = new D();
    }
```

여기에서 E 클래스를 역직렬화할때 필터로 들어오는것들의 depth를 확인하는 필터를 등록했어.
```java
ObjectInputFilter filter = filterInfo -> {
            System.out.println(filterInfo.serialClass().getName() + " : " + filterInfo.depth());
            return ObjectInputFilter.Status.UNDECIDED;
        };
```
결과가 
![image](https://user-images.githubusercontent.com/34976178/89396692-d4bd9480-d749-11ea-86c6-07ef86a595e4.png)
이런식으로 나오더라구, 아무래도 배열 자체를 depth로 체크하고 배열의 원소도 객체 참조라면 그 배열의 원소도 depth로 보는 것 같아.

그리고 HashSet 예제로 depth를 체크해봤는데 
![image](https://user-images.githubusercontent.com/34976178/89400676-316f7e00-d74f-11ea-9534-16e142433f3d.png)
이런식으로 쭈욱 증가하다가 

![image](https://user-images.githubusercontent.com/34976178/89400718-3f250380-d74f-11ea-8269-c7a5974ce819.png)

100 부터 점점 감소하는더라구? 프로그램이 더 이상 진행이 안되서 끝은 못봤다!
