### ISSUE TITLE
[아이템 86] readObjectNoData()

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#157]
> p.458 기존의 직렬화 기능 클래스에 직렬화 가능 상위클래스를 추가하는 드문 경우를 위한 메서드이다.

질문 : 이부분에 주석이 달려있는데 주석 링크 부탁드려여. 기존 직렬화 가능 클래스(자식) -> 직렬화 가능 상위클래스(부모) 일때 어떤 식으로 사용을 하는건지 감이 안와서..???

**Comment by Gobukgol** [comment]
[Java Object Serialization Specification: 3 - Object Input Classes](https://docs.oracle.com/javase/9/docs/specs/serialization/input.html#the-readobjectnodata-method)

**Comment by Gobukgol** [comment]
```java
public class Sub implements Serializable {
    String version;

    public Sub(final String version) {
        this.version = version;
    }
}
```
먼저, 이렇게 구성되어있는 Sub 클래스를 텍스트 파일로 직렬화해서 저장해두었어.

![image](https://user-images.githubusercontent.com/34976178/89384177-aa171000-d738-11ea-8d1b-00d0b821fc11.png)
![image](https://user-images.githubusercontent.com/34976178/89384195-b13e1e00-d738-11ea-87df-29b581c2c75e.png)

그 다음에 이 Sub가 Super 클래스를 상속한 뒤에 직렬화한 이전의 Sub 클래스를 현재 상속받은 클래스로 역직렬화 하면 아래와 같이 상위 클래스의 필드를 접근하면 NullPointerException이 발생하게되.

```java
public class Super implements Serializable {
    String defaultVersion = "1.0.0";
}

public class Sub extends Super implements Serializable {
    String version;

    public Sub(final String version) {
        this.version = version;
    }
}
```

![image](https://user-images.githubusercontent.com/34976178/89384427-0bd77a00-d739-11ea-8748-617863b36e04.png)
![image](https://user-images.githubusercontent.com/34976178/89384453-15f97880-d739-11ea-93ea-2d913e64fe09.png)

여기에서 Super 클래스에 readObjectNodata() 메소드를 추가해서 해당 필드의 정보를 넣는거지

```java
public class Super implements Serializable {
    String defaultVersion = "1.0.0";

    private void readObjectNoData() throws InvalidObjectException {
        defaultVersion = "1.0.0";
    }
}
```
그 결과 테스트를 통과할 수 있었어.

지금까지의 코드는 다음의 블로그 내용을 참고하였어.
[brunch](https://brunch.co.kr/@oemilk/179)
