### ISSUE TITLE
[아이템 87] 물리적 표현과 논리적 내용

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#159]
> p.459 **객체의 물리적 표현과 논리적 내용이 같다면 기본 직렬화 형태라도 무방하다.**

질문 : 물리적 표현과 논리적 내용이 각각 의미하는바가 뭔지 이해가 잘 안되네 설명해 줄 수 있어?

**Comment by pci2676** [comment]
아 읽다보니까 물리적 표현은 실제 구현 스펙을 말하는거고 논리적인건 외부에 노출(인터페이스)되는 모습을 의미하는 건가

**Comment by Gobukgol** [comment]
```java
public final class StringList implements Serializable {
    private int size = 0;
    private Entry head = null;
    
    private static class Entry implements Serializable {
        String data;
        Entry next;
        Entry previous;
    }
}
```

책 예제로 설명할 수 있을거 같아서 가져왔어.

뭔가 형이 얘기한게 맞는것 같아! 물리적 표현은 코드로 어떻게 구현했는지? 논리적 표현은 그게 무엇을 나타내는지? 인것 같아.
책의 예시가 Name 클래스는 firstName, middleName, lastName으로 구현하였는데 실제로도 이름은  firstName, middleName, lastName 로 구성되고 나타낼 수 있지.

근데 위 코드 처럼 문자열은 문자를 나열한 것이라고 표현할 수 있는데, 위 코드 같은 경우 Entry를 이용해서 양방향 연결리스트로 구현을 해서 각각의표현이 조금 다르다고 할 수 있는것 같아.
