### ISSUE TITLE
[아이템 85] 자바 직렬화 폭탄

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#160]
> p.[451] 자바직렬화 폭탄 예제

질문 : 왜 2^100 번 hasCode가 불리는거지?

**Comment by Gobukgol** [comment]
![image](https://user-images.githubusercontent.com/34976178/88317183-e0758800-cd53-11ea-8ac7-4883448390e8.png)

그림이 굉장히 구린데 각 Set이 원소 2개씩 들고있으니까 그림과 같이 그래프가 구성될것이고
각각의 원소들의 해시코드를 계산해야하니까 호출하는 횟수가 2^100 넘게 호출하는거지!
