### ISSUE TITLE
[아이템 89] 잘못된 싱글턴 코드

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#164]
> p.476 도둑 클래스 관련 코드

질문 : 이코드가 잘 이해가 안되는데 설명좀 부탁해.
왜 stealer에서 readResolve 한게 Elvis의 String[] 으로 저장이 되는지 뭔가 코드 흐름 자체가 이해가 안돼

**Comment by pci2676** [comment]
> p.475 먼저, readResolve 메서드와 인스턴스 필드 하나를 포함한 '도둑(Stealer)' 클래스를 작성한다. 이 인스턴스 필드는 도둑이 '숨길' 직렬화 된 싱글턴을 참조하는 역할을 한다. 직렬화된 스트림에서 싱글턴의 비휘발성 필드를 이 도둑의 인스턴스로 교체한다.

위 부분에서 **직렬화된 스트림에서 싱글턴의 비휘발성 필드를 이 도둑의 인스턴스로 교체한다.** 가 핵심인데,
**바이트 코드 자체**에서 싱글턴(`Elvis`)의 비휘발성 필드(`String[] favoriteSongs`) 부분을 도둑의 인스턴스(`ElvisStealer`)로 교체한다는 거야 나도 이 부분 읽고 `String` 타입 필드인데 `ElvisStealer` 가 들어가는게 이상하다고 생각하고 [자료](https://stackoverflow.com/questions/37660696/elvisstealer-from-effective-java)를 찾아봤거든!

위 자료에서 보면
우리가 바이트 코드를 바꾸면서 `Elvis(new).favoriteSongs = ElvisStealer(new)` 가 되어있는 상황에서 `readResolve` 를 호출하게 되면
`Elvis(new).favoriteSongs = ElvisStealer(new).readResolve()` 와 같은 흐름으로 코드가 실행이 되고
결국 `ElvisStealer`의 `readResolver`에서 반환하는 `String` 이 반환되는 구조였어!

역 직렬화에 대한 전체적인 흐름을 잘 설명해주는 글인것 같아서 같이 읽어 보면 좋을 것 같아!

**Comment by mjung1798** [comment]
Elvis 역직렬 화를 할 때  Stealer 가 불린다. 그 이유는 Elivs의 favoriteSong이 역직렬화 될 때, return String[] 에 대한 readResolve 코드를 찾기 위해서 ElivsStealer를 부르게 된다. 
그렇게 ElvisStealer에서의 readResolve가 불리게 되는것!

이 ElivsStealer의 readResolve가 하는 역할은 Elivs가 역직렬화 되는 도중의 과정인 readResolve에서 생성되는 다른 값을 저장하기 위해서 인데,
Stealer의 readResolve가 끝나고 올바르게 Elvis의 readResolve가 불리면 Elvis는 자신의 싱글턴 인스턴스를 반환한다.
그래서 만약 Stealer에서 impersonator 변수에 저장을 하지 않았더라면 stealer에서 생성된 인스턴스가 어디에도 저장이 되지 않아 GC에 의해 (싱글턴이 아닌) 다른 값으로 생성된 Elivs가 사라질텐데,
Stealer에서 싱글턴이 아닌 다른 값으로 생성된 Elivs를 impersonator에서 저장을 하고 있어 GC에 의해 사라지지 않는다.
