### ISSUE TITLE
[아이템 90] writeReplace

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#165]
> p.480 이메서드는 자바의 직렬화 시스템이 바깥 클래스의 인스턴스 대신 SeializationProxy의 인스턴스를 반환하게 하는 역할을 한다. 다시말해 직렬화가 이루어지기 전에 바깥 클래스의 인스턴스를 직렬화 프록시로 변환해 준다.

질문 : 음,, 그러면 이 이펙티브 자바의 직렬화 총 챕터를 요약했을 때 자바의 직렬화 과정이 writeReplace 확인 ->  readObject를 이용한 기본 직렬화 -> readResolve를 이용한 대체
이 과정으로 직렬화를 확인하는건가??

그리고 직렬화 프록시 패턴용 writeReplace 메서드를 작성했는데 해당 메서드를 사용한 예제가 없어서 간단하게 아래 코드 참고해서 이 메서드를 추가 했을 때 어떤 변화가 일어나는지를 알고싶어.

**Comment by pci2676** [comment]
1. 직렬화는 writeObject를 하고  writeReplace가 직렬화 값을 바꾸는 거고
역직렬화는 readObjcet를 수행하는데 readResolve가 역직렬화 한 값을 바꾸는 거야!
직렬화
 - wirteObject
 - writeReplace (가로채기)
역직렬화
 - readObject
 - readResolve (가로채기) 

2. 직렬화 프록시 패턴용 writeReplace 메서드의 예제는 다음과 같아
```java
public class Foo implements Serializable {
    public static final Foo INSTANCE = new Foo("FIX");
    private String value;

    public Foo(final String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    static class FooProxy implements Serializable{
        private String value;

        public FooProxy(Foo foo) {
            this.value = foo.value;
        }


        private Object readResolve(){
            return new Foo(this.value);
        }
    }

    private Object writeReplace() {
        return new FooProxy(this);
    }

}
```
Proxy 쪽의 readResolve()를 구현해서 논리적인 값만을 반환하도록 해주면 끝이야!
