### ISSUE TITLE
[아이템 88] 정상 인스턴스에서 시작된 바이트 스트림

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#166]
> p.470 정상 인스턴스에서 시작된 바이트 스트림 끝에 private Date 필드로의 참조를 추가하면 가변 Period 인스턴스를 만들어낼 수 있다.

질문 : 이부분 예제 코드에 내부 Date 필드의 참조를 추가하는 방법이 이해가 안가요!!

**Comment by pci2676** [comment]
p.470 코드 88-4 를 보면 Date 필드를 `ByteArrayOutputStream bos`에 `write`하는 것을 확인할 수 있어!

```java
ByteArrayOutputStream bos = new ByteArrayOutputStream();

...

byte[] ref = { 0x71, 0, 0x7e, 0, 5 }; // 참조 #5  <- 이게 추가할 Date의 바이트 값이고
bos.write(ref); // 시작(start) 필드 <- 이 부분에서 필드의 참조를 추가하는거야

...
```
