### ISSUE TITLE
1.1~1.3 용어정리

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#168]
토비의 스프링보면서 객체지향, 디자인 패턴등에 대한 용어들이 많이 나오는데 한번 싹 정리해서 기억 안 날때마다 한번씩 볼 수 있도록 예제와 정리해두면 좋을 것 같다.(면접 시 참고)

1. 템플릿 메서드 패턴

2. 펙토리 메서드 패턴, 자바의 팩토리 메서드

3. 개방 폐쇄 원칙

4. 응집도 결합도

5. 전략 패턴

**Comment by mjung1798** [comment]
https://github.com/Java-Bom/ReadingRecord/pull/170
