### ISSUE TITLE
[1.4~7] 용어정리

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#169]
- 추상 팩토리 패턴 (13ea7ab)
- 제어의 역전 (d248362)
- 빈 팩토리, 애플리케이션 컨텍스트, 컨테이너, IoC 컨테이너, 스프링의 빈 (8fd75ec}
- 오브젝트 동일성과 동등성, 싱글톤 레지스트리 (dca60a6)
- 싱글톤 패턴 (5b76c7d)
- 빈의 스코프 (46f6ee8)

**Comment by chldbtjd2272** [comment]
1.애플리케이션 컨택스트의 장점 100p
2.싱글톤 패턴의 한계 107p
3.DI 세가지 조건 114p
