### ISSUE TITLE
[1.4~7] DI 장점

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#174]
125P 에 DI 장점, 관심사의 분리에 대해서 나오는데 이거 엄청 중요한거 같아.
예제랑 자세한 설명추가해줘

**Comment by csbsjy** [comment]
책 예제랑 멀어지기가 힘든데 ㅎㅅㅎ ,,

```java
public interface PaySystem {
    void pay();
}
``` 
이런 인터페이스가 있고 NaverPaySystem, KakaoPaySystem 구현체가 있다고 했을 때
얘네들의 관심사는 "결제"이고 높은 응집도로 결제에 관련된 로직만 가지고 있다고 해볼게.


근데 kakao, naver 각각의 결제 로깅을 따로해서 추이를 보고싶다는 요구가 생겼을 때
가장 간단한 방법은 kakaoPaySystem, NaverPaySystem 의 pay 메서드에 logging 을 추가하는건데
사실 로깅은 두 결제 시스템의 관심사가 아니고, 만약 수십개의 결제시스템이 있다고 가정하면 오히려 더 복잡해지고 실수가 일어날 수 있어.


그래서 아래처럼 Logging 이라는 새로운 관심사를 담당하는 PaySystem 을 만들면 기존의 PaySystem 을 수정하지 않아도 돼.
LoggingPaySystem 역시 DI 를 통해 실제로 "결제"라는 관심사를 수행할 PaySystem 타입의 의존 오브젝트를 런타임에 사용하고
본인은 로깅이라는 역할만 수행해. DI를 사용했기 때문에 PaySystem의 구현체는 pay 라는 로직만 가지고, LogginPaySystem은 logging 이라는 로직만 직접수행하는 높은 응집도의 객체가 될 수 있어.

```java
@Slf4j
public class LoggingPaySystem {
    private final PaySystem paySystem;

    public LoggingPaySystem(PaySystem paySystem) {
        this.paySystem = paySystem;
    }

    public void logginAndPay() {
        log.debug("{}, {}", paySystem.getClass(), LocalDateTime.now());
        paySystem.pay(); // pay 로직은 paySystem 에 넘긴다
    }
}
```
