### ISSUE TITLE
[1.4~7] 싱글톤 패턴의 한계

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#175]
싱글톤 패턴의 한계에 대해 설명하는데, 클래스로더와 분리된 jvm환경일 때 싱글톤 패턴을 깰 수 있다.
이런 문구가 나오는데 이 예제에 대해 자세히 설명해주면 좋을거같아

**Comment by csbsjy** [comment]
분리된 jvm 은 말그대로 다른 jvm 에서 싱글톤 인스턴스를 만들었음에도 분산된 다른 JVM 은 그 인스턴스 위치를 찾을 수 없을수도 있어서 새로 만들 수 있다. 클래스로더도 비슷하게 다중 클래스로더일 때 다른 Singleton 복사본을 가지고 클래스로딩하면서 초기화시키면서 싱글톤이 꺠질 수 있다. 
https://www.oracle.com/technical-resources/articles/java/singleton.html <- 요거 좀 재밌어보여서 자세히 읽고 추가할게

**Comment by csbsjy** [comment]
userdao로 바꾸기
