### ISSUE TITLE
[1.8 ~ 2.2] 용어정리

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#176]
- XML를 이용해서 Bean 설정 (b7d7163)
  - GenericXmlApplicationContext, ClassXmlApplicationContext
    - GenericXmlApplicationContext 는 xml 패키지 경로를 인자로 주어서 Bean 정보를 가져올 수 있음
    - ClassXmlApplicationContext 는 인자로 뒤에 따라올 클래스의 패키지 경로에 대해 상대적인 경로로 Bean 정보를 가져올 수 있음
    - ClassXmlApplicationContext 로 인자로 준 클래스의 상대경로로 xml 패키지 경로를 지정하여도 xml은 resources 디렉토리 하위에 있어야함
- 테스트 (193b048)
  - 단위 테스트
  - 포괄적인 테스트(comprehensive test)
    - 성공하는 단 하나의 테스트가 아니라 테스트 대상에서 발생할 수 있는 상황에 대해서 테스트를 하는 것

**Comment by Gobukgol** [comment]
- XML를 이용해서 Bean 설정
- DTD와 스키마
- GenericXmlApplicationContext, ClassXmlApplicationContext
- DataSource 인터페이스
- 풀링(Pooling)
- SimpleDriverDataSource
- DataSource 빈 설정
- 단위 테스트
- 포괄적인 테스트(comprehensive test)

**Comment by Gobukgol** [comment]
- 프레임워크와 라이브러리의 차이점
- 스프링 프레임워크도 부트 처럼 Dependency Management가 가능한지

**Comment by Gobukgol** [comment]
- 프레임워크와 라이브러리의 차이점
  - 프레임워크는 내가 짠 코드가 프레임워크 위에서 실행 되는 것, IoC의 개념이 적용되었다.
  - 라이브러리는 내가 필요한 라이브러리를 가져다가 내 코드에서 사용하는 것

- Dependency Management 는 스프링 프레임워크에서 안되는 것 같다. Spring Boot의 버전을 보고 관리하는 듯...??
