### ISSUE TITLE
[1.8 - 2.2] 스프링 프레임워크의 장점

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#177]
p.143 의 마지막에서 두번째 단락을 읽어보면 스프링이 어떤 관심을 가지고있고, 개발자 어떻게 하도록 도와주는 도구인지 등등 설명이 되어있는데 
누가 스프링 프레임워크 왜써요? 라고 물어보면 어떻게 대답할 수 있을지 설명을 이 페이지를 참고해서 간단하게 정리할 수 있을 것 같아. 해주세요!

**Comment by Gobukgol** [comment]
A 인터페이스를 의존하는 여러 객체들이 존재할 때 A 인터페이스의 구현체를 교체해야하는 상황에서 Bean 설정 정보만 바꿔주면 쉽게 구현체를 교체할 수 있다....???

**Comment by Gobukgol** [comment]
장점 다시 추가

**Comment by Gobukgol** [comment]
dependency management를 루트 프로젝트에서 사용하고 core에 대한 버전을 명시하면 하위 프로젝트에서 core 버전을 따로 명시 안해도 된다.
- 코드 달아 두기-
