### ISSUE TITLE
[2.3 ~ 2.6] 용어정리

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#179]

**Comment by chldbtjd2272** [comment]
TDD (테스트 주도 개발)
- 기능 개발 보다 테스트를 먼저 작성하는 방식
- 테스트를 먼저 작성하므로 놓치는 테스트 없이 모든 테스트를 작성할 수 있다.
- 테스트 작성과 이를 성공시키는 기능코드 작성의 주기를 짧게 가져가도록 하여 자연스럽게 단위 테스트를 작성한다.
- 단위테스트 위주 작성은 전체 코드의 구조 개선에 도움이 된다.
