### ISSUE TITLE
[아이템10] 동기화용 lock 필드

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#18]
여기서 말하는 동기화용 락 필드는 뭘까?

**Comment by mjung1798** [comment]
> p.63

**Comment by mjung1798** [comment]
정말 말 그대로 두 객체를 thread에서 실행을 할 수 있는 상황이라 ```private boolean lock``` 등의 멤버 변수를 정의해준 상태에서(자바의 synchronized를 직접 구현했을 때) equals를 사용하는 순서를 말하는듯! 
객체의 논리적 동등성 값을 비교할 때, ```Integer{int num, boolean lock}``` 이런식의 클래스가 있다고 했을때 핵심적인 값부터 비교(다를 가능성이 높은 값)하는게 더 올바른거지, 핵심값이 아닌 lock 값부터 비교하는건 아니라서..?!
근데 자료형으로만 봐도 lock은 타입이 boolean이라 2가지라서 다를 가능성이 50%인데, int num 같은경우는 int 타입이면 2^32 가지 즉 0.2^-7% 임! 자료형의 타입부터가 논리적으로 비교했을 때 다를 가능성이 lock 자체는 작으니까 한 말일 수도 있을 것 같다!

**Comment by mjung1798** [comment]
lock 필드는 비교할 필요가 없다. // 논리적 상태를 대표하는 값이 아니기 때문이다.

**Comment by chldbtjd2272** [comment]
https://github.com/Java-Bom/ReadingRecord/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%20%EC%9E%90%EB%B0%94/effectiveJava/src/test/java/item10/lock/UnLockAccountTest.java
