### ISSUE TITLE
[2.3 ~ 2.6] 테스트 시 애플리케이션 컨텍스트 내의 빈이 할당한 리소스를 제거하지 않으면 생기는 문제

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#180]
> p.184 
애플리케이션 컨텍스트를 테스트 수행할 때마다 생성하면 문제가 발생할 수 있다고 써있는데 어떤 문제가 발생할 수 있는지 설명해줘

**Comment by chldbtjd2272** [comment]
컨택스트를 매번 생성하는게 문제가 된다고 나오진 않고, 많은 리소스가 투자되는 빈이 있을때 제대로 정리되지 않고 다음 테스트에 새로운 테스트가 생성되는게 문제야.

자체 스레드를 생성하는 빈이라던지 리소스가 많이 투자되는 빈이 제대로 정리되지 않고 다음 테스트가 진행되면 많은 영향을 받을 수 밖에 없어.

추가적으로 애플리케이션 컨택스트를 매번 테스트마다 새로 띄우는 것도 별로 좋아보이지 않는데, 우선 테스트의 속도가 너무 느려져 어떻게 관리하면 좋을지는 내일 예제로 보여줄게

**Comment by chldbtjd2272** [comment]
테스트 환경에서 컨택스트가 변경될 경우

- properties가 변경 될 경우
- 기존 테스트와 다른 bean으로 교체될 경우(ex mockBean 사용)
