### ISSUE TITLE
[2.3 ~ 2.6] AoP 와 DI

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#181]
> p. 190

AoP에 적용된 DI 에 대해 설명해주세요

**Comment by chldbtjd2272** [comment]
aop에 시작은 전략패턴 부터 시작이야
앞에 나온 전략패턴으로 관심사 분리를 하는데, 이 부분이 DI적용을 필수로 필요해
CountingConnectionMaker- ConnectionMaker 예제를 생각해보면 쉽게 이해될거야

전략패턴 -> 프록시/데코레이터 패턴 -> aop 까지 변화되는 과정은 너무 광범위한 범위라 aop 장 들어갈때 보는게 좋을거같아
