### ISSUE TITLE
[아이템 62] 전역 이름공간(namespace)

### ISSUE THREAD

**Issue by Hyeon9mak** [Java-Bom/ReadingRecord#182]
> p.363, 이 방식의 문제는 스레드 구분용 문자열 키가 전역 이름공간에서 공유된다는 점이다.

안녕하세요,  **전역 이름공간** 이라는 표현이 이해가 잘 되지 않아 이슈 등록하게 되었습니다.  

자바에서 package가 이름공간의 역할을 수행하는 것으로 알고 있는데,  
*'전역 이름공간에서 공유된다.'* 라는 표현을 package에 빗대서 어떻게 이해하면 될까요?

1. 같은 package에 속하는 모든 클래스가 공유한다.
2. 자바에는 **지역 이름공간 / 전역 이름공간** 개념이 존재한다.

개인적으론 1번에 가깝지 않을까 생각하는데, 혹시 다르게 이해해야하는 것인지 궁금합니다.

**Comment by pci2676** [comment]
저는 스레드 구분용 문자열 키(java.lang.String)가 전역(heap 메모리) 이름공간에서 공유된다. 라고 생각하며 읽었습니다.
java.lang.String을 이름공간(namespace) 라고 생각하시면 되지 않을까 싶네요.

https://en.wikipedia.org/wiki/Namespace#Examples
![image](https://user-images.githubusercontent.com/13347548/99906409-5138ab00-2d1a-11eb-926e-9b94f098b6d2.png)

**Comment by Hyeon9mak** [comment]
아.. Heap은 생각치도 못 했습니다.
단순하게 **namespace**에만 초점을 맞추고 생각해서 이해가 안되었는데,
말씀해주신대로 생각해보면 '전역 이름공간'이라는 표현이 말이 되는 것 같습니다.

늦은 시간에도 답변 주셔서 감사합니다! 👏
