### ISSUE TITLE
[3.1 ~ 3.4] 용어 정리

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#183]

**Comment by chldbtjd2272** [comment]
1. 템플릿 메서드 패턴
2. 마이크로 DI * P223 예제로 구현한 예제로 앞에 나온 전략패턴과 비교해보면 좋을거 같아
3.로컬 클래스, 중첩클래스 (3가지)

**Comment by pci2676** [comment]
1. 템플릿 메서드 패턴 [`dff440a`](https://github.com/Java-Bom/ReadingRecord/pull/185/commits/dff440ac2640e341cb4c31846f4a2b210cc9aa0a)
 - 패턴은 1장에서 이미 정리 되어있음
