### ISSUE TITLE
[3.1 ~ 3.4] PreparedStatement,ResultSet 반환

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#184]
> p.213 

질문 : db 연결 후 반환할 리소스로 PreparedStatement,ResultSet가 있는데 이것들을 반환해야 하는 이유

**Comment by pci2676** [comment]
DB Vender 마다 문제가 다르게 발생한다고 하는데 대표적으로는
Oracle 같은 경우에 [maximum open cursors exceeded](https://stackoverflow.com/questions/12192592/java-sql-sqlexception-ora-01000-maximum-open-cursors-exceeded) 가 발생하는데 ResultSet을 닫지 않으면서 발생하는데 한 Session에서 열고 있을수 있는 Cursor(아마 한 Row를 가리키고 있는 그것을 나타내는 것 같아)의 갯수가 초과해 버리면서 발생하는 문제가 있데.

그리고 무엇보다 GC에 의해서 수거가 되기도 하겠지만 사용하지 않는 객체가 계속 열려있으면서 메모리 누수가 발생할 수도 있을것 같아.

> https://stackoverflow.com/questions/4507440/must-jdbc-resultsets-and-statements-be-closed-separately-although-the-connection

**Comment by pci2676** [comment]
PreparedStatement는 DBMS가 MySQL의 경우 mysql_stmt라는 자원을 사용한다고 하는데 mysql_stmt_execute() 라는 메서드를 사용해서 커서를 오픈한데 : [MySql](https://dev.mysql.com/doc/c-api/8.0/en/c-api-prepared-statements.html), [MySql Korea](http://www.mysqlkorea.com/sub.html?mcode=manual&scode=01_1&m_no=23309&cat1=1399&cat2=1401&cat3=1424&lang=k)
ResultSet이 사용하는 Cursor랑 관련이 되있는걸 보면 Session과 연결되어있지 않을까 싶어...
