### ISSUE TITLE
[3.1 ~ 3.4] Statement Pool

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#186]
> p.210 

질문 : close 시 Connection pool, Statement pool 에 반납 ~ 이런 내용이 나오는데, Connection pool 에 비해 Statement pool 은 많이 못들어본거같아서. 대충 찾아보니까 자주 사용하는 Statement 를 미리 만들어두고 꺼내쓰는 Statement pooling 기법이있던데 그 얘기를 하는건가? 간단한 설명 부탁ㅎ ㅐ~

**Comment by pci2676** [comment]
http://itdoc.hitachi.co.jp/manuals/3020/30203Y0410e/EY040199.HTM#ID00836

흠.. 여기 보면 Connection내부에 PreparedStatement pool을 두고 PreparedStatement를 처음 한번만 만들고 계속 재사용한다고 적혀있는데 이걸 말한거 같아

![image](https://user-images.githubusercontent.com/13347548/101643902-f15f3580-3a77-11eb-9cab-027669d8d6f5.png)
