### ISSUE TITLE
[4.1 ~ 4.3] 용어 정리

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#191]

**Comment by pci2676** [comment]
낙관적 락킹 ➡️ 추가로 비관적 락킹에 대해서도 정리해주면 좋을 듯

**Comment by csbsjy** [comment]
Error Exception RuntimeException

**Comment by csbsjy** [comment]
예외복구 예외회피 예외전환

**Comment by Gobukgol** [comment]
- 예외 복구, 예외 회피, 예외 전환 (6ca3cf6)
  - 예외 복구 : 예외 상황이 발생하면 문제를 해결하고 정상 상태로 돌려놓는 것, 네트워크 접속 중 예외가 발생했을 경우 다시 접속 시도하여 예외상황으로 부터 복구
  - 예외 회피 : 예외 상황이 발생하면 문제를 해결하지 않고 자신을 호출한 쪽으로 문제 해결을 위임하는 것
  - 예외 전환 : 예외 상황이 발생하면 문제를 해결하지 않지만 해당 예외를 다른 예외로 전환하여 던지는 것
- 락킹 기법
  - 낙관적 락킹 : 트랜잭션이 충돌이 나지 않는다고 가정하고 어플리케이션에서 제공하는 락 방식, 데이터를 읽는 시점에 락을 걸지 않기 때문에 트랜잭션을 커밋하기 전까지는 알 수 없다. (ca53014)
    - 엔티티에 @Version 어노테이션이 있는 필드를 추가하는 것만으로 낙관적 락킹을 적용할 수 있다.
    - 엔티티 수정시 version 필드값이 증가, 맨 처음 조회했을 때 version 값이랑 커밋 전 version 값이 다를 때 OptimisticLockingFailureException throws
  - 비관적 락킹 : 트랜잭션이 충돌이 날 것이라고 비관적으로 생각하고 우선 락을 거는 방식, 데이터베이스에서 락을 건다. (f87e345)
    - Repository 메소드에 @Lock 어노테이션을 통해서 설정 가능
    - 설정시 조회 코드에서 Select for update 쿼리가 나간다.

**Comment by Gobukgol** [comment]
비관적 락킹

- 비관적 락킹 기법에는 2가지의 LockMode가 존재한다.
- 공유 Lock/읽기 Lock (PESSIMISTIC_READ)
  - 여러 트랜잭션이 한 데이터를 읽을 때에 한해서 동시에 접근할 수 있다. 하지만 한 트랜잭션이 끝나지 않았을 때 다른 트랜잭션이 해당 데이터를 수정할 수 없다.
- 베타 Lock/쓰기 Lock (PESSIMISTIC_WRITE)
  - 트랜잭션이 한 데이터를 점유하고 있을 때 다른 트랜잭션은 해당 데이터를 읽거나 쓸 수 없다.
- 다른 트랜잭션이 Lock을 획득하기 위해 대기하다 지정된 Lock Timeout 시간을 초과하면 **PessimisticLockingFailureException** 을 던진다.
