### ISSUE TITLE
[4.1 ~ 4.3] jpa 낙관적 잠금

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#194]
> p.[306] 

질문 : jpa 등 object 기반 update 실행 시 낙관적 잠금을 설정해서 사용할 수 있다.

mysql 기본 트랜잭션 격리레벨은 READ COMMITTED고 특정 기능에서 더 높은 수준의 격리레벨을 원할 경우 잠금설정들을 걸 수 있어
하이버네이트에서는 낙관적 잠금과 비관적 잠금을 제공하는데 해당 설정을 하려면 코드에 몇가지 추가해줘야해
해당 예제들 짜보고 실제 잠금이 잘 동작하는지 테스트해서 공유해주면 좋을거같아

**Comment by Gobukgol** [comment]
[issue comment](https://github.com/Java-Bom/ReadingRecord/issues/191#issuecomment-757355900)
