### ISSUE TITLE
[5.3 ~ 5.5] 용어정리

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#199]
- 서비스 추상화
- 패턴
   - 브릿지패턴
   - 미디에이터 패턴
- 테스트 대역(test double)
   - Stub
   - Mock

**Comment by csbsjy** [comment]
JNDI

**Comment by Gobukgol** [comment]
- 서비스 추상화
  - 어플리케이션의 비즈니스 로직이 트랜잭션과 같은 기술 구현에 종속되지 않게 하기 위해 인터페이스와 구현체를 두어 추상화 시키는 것. 해당 기술을 사용하는 비즈니스 로직은 인터페이스를 통해 일관된 방법으로 접근한다.
- 패턴
  - 브릿지패턴 9f5e313
   - 구현부에서 추상층을 분리하여 각자 독립적으로 변화할 수 있게 하는 패턴이다. 
   
![image](https://user-images.githubusercontent.com/34976178/104831336-3f632680-58cb-11eb-9669-3f31f29570a0.png)

  - 미디에이터 패턴 4ed22e7
   - 복잡한 M:N의 관계에서 중재자 역할을 하는 객체(Mediator)를 두어 M:1의 관계로 풀고 중재자 객체가 연관된 다른 객체들과의 통신을 관리한다.
    - 각 객체들은 중재자를 제외한 다른 객체를 모른다

![image](https://user-images.githubusercontent.com/34976178/104831344-4c801580-58cb-11eb-8baf-1c8d97573bed.png)


- 테스트 대역(test double) - 테스트를 진행하기 어려운 경우 이를 대신해 테스트를 진행할 수 있게하는 객체
  - Dummy
    - 인스턴스화된 객체가 필요하지만 기능은 필요하지 않은 경우
    - Dummy 객체의 메소드가 호출되었을 때 정상동작을 보장하지 않는다
    - 객체가 전달되지만 사용되지는 않는 객체
  - Fake
    - 실제 객체와 동일하게 동작하도록 구현된 객체
    - 복잡한 로직을 단순화하여 구현하였기 때문에 실제 코드에서 사용되기엔 부적절하다
  - Spy
    - Stub의 역할을 하면서 호출된 내용에 대해 약간의 정보를 기록한다
    - Spy로 구현된 객체에 자기 자신이 호출되었을 때 확인이 필요한 부분을 기록하도록 구현한다
    - 실제 객체처럼 동작시킬 수 있고, 필요한 부분에 대해서는 Stub으로 만들어 동작을 지정할 수 있다
  - Stub
    - Dummy 객체가 실제로 동작하는 것 처럼 구현한 객체
    - 인터페이스 또는 클래스가 최소한으로 구현되어있음
    - 테스트에서 호출에 대해 미리 준비해둔 결과를 반환
  - Mock
    - 호출에 대한 기대를 명세하고 내용에 따라 동작하도록 구현된 객체
    - 행위를 검증하기 위해 사용되는 객체
    - Mock 객체를 만들어주는 프레임워크로 Mockito 가 있음

**Comment by Gobukgol** [comment]
[우아한 형제들 Test Double](https://woowacourse.github.io/javable/post/2020-09-19-what-is-test-double/)
