### ISSUE TITLE
[아이템11] 핵심필드 생략에 따른 hash 성능저하 문제

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#20]
> p.72 특히 어떤 필드는 특정 역역에 몰린 인스턴스들의 해시코드를 넓은 범위로 고르게 퍼트려주는 효과가 있을지도 모른다.

성능상에 문제가 있을 거라는건 수긍이 되지만 딱 떠오르는 예시가 생각나지 않아서!

**Comment by chldbtjd2272** [comment]
예전 String 16자만 골라서 해쉬를 하고 이 경우 url은 계층적으로 javabom/ReadingRecord/issues 처럼 중첩되는 부분이 많아 해쉬값이 같아지는 경우가 많아 이 경우에는 같은 해쉬값을 가지게 되고 결국 해쉬충돌이 일어나 링크드 리스트에 데이터를 저장 선형적인 탐색시간이 나타날수밖에없어
