### ISSUE TITLE
[5.4] @DirtiesContext

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#200]
> p.396

언제 사용하고 어떤 동작을 수행해주는지 설명좀!

**Comment by Gobukgol** [comment]
먼저 토비의 스프링 ```pg.186 ~ 192``` 에서 @DirtiesContext 에 대한 내용이 나와서 여길 참고했어!

- 스프링 테스트는 applicationContext를 테스트마다 생성하지않고 재사용한다.
- 따라서 같은 context를 사용하는 테스트들 중에 한 테스트가 applicationContext를 직접 변경하는 경우 다음 테스트에서 변경된 context를 사용하기 때문에 테스트가 정상적으로 수행되지 않을 수 있다
- 이때 @DirtiesContext 어노테이션을 사용하면 테스트 마다 새로운 applicationContext를 생성하여 사용하게 할 수 있다

다음과 같은 간단한 테스트 클래스 두개를 만들었어.

```java
@SpringBootTest
public class DirtiesContextTest {
    @Autowired
    ApplicationContext applicationContext;

    @BeforeEach
    void setUp() {
        System.out.println(this);
        System.out.println(applicationContext);
    }

    @DisplayName("빈 테스트 1")
    @Test
    void emptyTest1() {
    }

    @DisplayName("빈 테스트 2")
    @Test
    void emptyTest2() {
    }
}

@SpringBootTest
public class AnotherDirtiesContextTest {
    @Autowired
    ApplicationContext applicationContext;

    @BeforeEach
    void setUp() {
        System.out.println(this);
        System.out.println(applicationContext);
    }

   // ... 같은 메소드
}
```
그리고 이 테스트를 실행하면 다음과 같이 결과가 나와. Test 클래스는 테스트 메소드마다 매번 새로 생성해서 그 주소값이 다른 반면에 ApplicationContext의 경우 항상 같은 객체를 사용해.

![image](https://user-images.githubusercontent.com/34976178/104832472-ab965800-58d4-11eb-9d83-37fcc0cace9e.png)

![image](https://user-images.githubusercontent.com/34976178/104832490-cb2d8080-58d4-11eb-86bd-0f75d6ce2541.png)

이때 각 테스트 클래스에 ```@DirtiesContext``` 어노테이션을 사용하면

![image](https://user-images.githubusercontent.com/34976178/104832576-54dd4e00-58d5-11eb-9776-96053c573ab1.png)

![image](https://user-images.githubusercontent.com/34976178/104832584-69b9e180-58d5-11eb-83d0-674f991941cd.png)

테스트 클래스마다 ApplicationContext를 새로 생성하는걸 볼 수 있어.

@DirtiesContext 관련 문서 [spring docs - @DirtiesContext](https://docs.spring.io/spring-framework/docs/current/reference/html/testing.html#spring-testing-annotation-dirtiescontext)
