### ISSUE TITLE
[6.3] 용어정리

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#202]
- 프록시와 프록시 패턴
- 데코레이터 패턴

**Comment by chldbtjd2272** [comment]
-  데코레이터 패턴
타깃에 부가적인 기능을 런타임 시 다이내믹하게(코드상에는 나타나지 않게) 부여해주기 위해 프록시를 사용하는 패턴
*  같은 타입을 상속받은 인스턴스를 각자의 기능에 맞게 구현하고 서로 조합하여 기능을 동적으로 생성할 수 있는 방법

- 프록시 
클라이언트와 사용 대상 사이에 대리 역할을 맡은 오브젝트를 두는 방법의 총칭(부가 기능을 추가하는 대리객체,접근제어를 하는 대리객체 전부 프록시라고 부른다)

- 프록시 패턴
타깃에 대한 접근 방법을 제어하려는 목적을 가진 경우 프록시 패턴 
(타깃에 대한 레퍼런스만 필요하고 진짜 호출될때 원본객체로 갈아낄 필요가 있을때 사용 ex) Jpa lazy loading)


- 프록시의 문제점
1. 타깃의 모든 메서드를 구현해야한다.
2. 부가기능에 대한 중복코드

- 리플랙션
자바의 코드 자체를 추상화해서 보는것 
class,method 등을 객체로 추상화하여 실제 class의 타입, 필드 등을 알아낼 수 있다.

- JDK 다이내믹 프록시


- 펙토리 빈 한계
하나의 타깃에 여러 개의 부가기능 적용시  빈 설정 코드가 지저분해진다.
클래스 단위로 밖에 부가기능을 걸 수 있다.
Handler 인스턴스가 빈 갯수만큼 생성되어야한다.(각 타깃의 타입이 다르기 때문에 같은 부가기능이라도 타겟 타입을 가지고 있기 위해 각각생성)
