### ISSUE TITLE
[6.3] 팩토리빈

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#203]
> p.451 리스트 6-13 Message의 팩토리 빈 클래스

질문 : 코드 보면 isSingleton() 코드로 돌려주는 오브젝트가 싱글톤인지를 알려준다고 했는데, 싱글톤으로 설정했을때랑 싱글톤으로 설정하지 않았을때 해당 message 클래스의 hashcode값을 비교하는 테스트 작성해두면 좋을 것 같아

참고 사이트 https://www.baeldung.com/spring-factorybean

그리고 isSingleton() 설명에서 "이것은 팩토리 빈의 동작방식에 대한 설정이고 만들어진 빈 오브젝트는 싱글톤으로 스프링이 관리해줄 수 있다" 이부분 조금 헷갈려, 여기서 말하는 만들어진 빈 오브젝트는 MessageFactoryBean을 얘기하는건가?

**Comment by chldbtjd2272** [comment]
FactoryBean의 isSingleton 메서드를 호출해 해당 빈이 싱글톤으로 유지되어야 하는지 아닌지를 판별하여 FactoryBean에서 빈을 생성해낸다.
FactoryBean은 singleton으로 유지되어야 하는지에 대한 설정정보 제공과 Bean 생성만 제공하고, 실제 싱글톤 유지와 관리는 스프링 컨테이너에서 한다는 의미야
