### ISSUE TITLE
[6.4] ProxyFactoryBean의 탬플릿/콜백 구조

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#205]
> p. 465 ProxyFactoryBean 은 작은 단위의 템플릿/콜백 구조를 적용....

질문 : 해당 클래스가 작은 단위의 템플릿/콜백 구조를 응용해서 적용했다고 하는데 그런 부분을 보여주고 설명해주면 좋을 것 같아

**Comment by pci2676** [comment]
템플릿/콜백 구조를 응용해서 변하는 부분(콜백), 변하지 않는 부분(템플릿)을 분리해냈다고 보면되는데,
아래와 같은 Advice 가 존재한다고 했을때 `invocation.proceed` 가 콜백에 해당하는데, 타겟에 해당하는 여러가지 메서드라고 보면될것 같아.   
부가기능들은 전부 `MessageAdvice.invoke(MethodInvocation invocation)` 이라는 템플릿의 형태를 띈다고 보면 될것같아.

```java
public class MessageAdvice implements MethodInterceptor {
    @Override
    public Object invoke(MethodInvocation invocation) throws Throwable {
        String ret = (String) invocation.proceed(); // 타겟의 여러가지 메서드
        return ret.toUpperCase();
    }
}
```
