### ISSUE TITLE
[6.6 ~ 6.7] 용어정리

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#209]

**Comment by Gobukgol** [comment]
- 트랜잭션 전파 (Transaction Propagation)
    - PROPAGATION_REQUIRED
        - 진행 중인 트랜잭션이 없으면 새로 시작하고, 이미 시작된 트랜잭션이 있으면 이에 참여한다
    - PROPAGATION_REQUIRES_NEW
        - 항상 새로운 트랜잭션을 시작한다.
    - PROPAGATION_NOT_SUPPORTED
        - 트랜잭션 없이 동작하도록 만든다. 진행 중인 트랜잭션이 있어도 무시한다.
- 격리수준
    - READ UNCOMMITTED
        - 각 트랜잭션의 변경 내용이 commit 이나 rollback 여부에 상관없이 다른 트랜잭션에서 보여진다.
        - A 트랜잭션에서 user 테이블에 이름이 '라라' 라는 사람을 추가 하고 commit 하기도 전에 B 트랜잭션에서 '라라'라는 사람을 조회 하고 사용할 수 있다.
        - 데이터베이스의 일관성을 유지할 수 없음
        - Dirty Read 발생 가능
           - 어떤 트랜잭션이 처리한 작업이 완료되지 않았는데도 다른 트랜잭션에서 볼 수 있게 되는 것.
    - READ COMMITTED
        - 트랜잭션에서 변경한 내용이 commit되기 전까지 다른 트랜잭션은 해당 변경 내용을 조회 할 수 없다, Undo 영역에서 변경 이전 내용을 조회한다.
        - 유저 테이블에서 A 트랜잭션에서 '라라' 라는 사람의 이름을 '팀' 으로 변경하고 commit이 되기 전에 B 트랜잭션에서 '라라'였던 것을 조회하면 Undo 영역에서 백업된 라라를 조회한다.
        - Non-Repeatable-Read  발생 가능
           - 한 트랜잭션 내에서 두번 조회를 했는데 첫번째 조회 결과와 두번째 조회결과가 다른 경우
           - 처음 '팀'을 조회햇을때 없었지만, 다음 조회때는 생긴 것
    - REPEATABLE READ
      - 트랜잭션 내에서 다른 트랜잭션이 데이터를 변경 했더라도 트랜잭션 시작 직전 시점의 데이터를 보여준다.
      - 트랜잭션은 고유한 번호를 가지고 있고 트랜잭션 시작 후 자신의 번호보다 작은 번호의 트랜잭션이 변경한 것만 읽는다.
      - 기존 유저 테이블에 '라라' 라는 사람을 6번 트랜잭션이 추가한 상황에서 12번 트랜잭션 A와 10번 트랜잭션 B가 시작을 했다. 다음에 12번 트랜잭션이 '라라'의 이름을 '팀'으로 변경하고 commit을 한 상황에서 10번 트랜잭션이 '라라'를 '라라'의 id로  조회 하려고 하면 A가 commit 되었음에도 불구하고 이전 내용이었던 6번 트랜잭션의 '라라'가 조회된다.
      - Phantom Read 발생 가능
          - 특정 범위의 레코드를 두번 조회할때 처음에는 없던 레코드가 두번째에 생긴 경우
    - SERIALIZABLE
      - 트랜잭션이 수행되는 동안 다른 트랜잭션이 데이터 조회 추가 변경 삭제를 못하도록 한다.
      - 완벽한 일관성을 제공
