### ISSUE TITLE
[아이템 11] 해시테이블에서 연결리스트처럼 동작한다? 

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#21]
> p.68, 모든 객체에게 똑같은 값만 내어주므로 모든 객체가 해시테이블의 버킷 하나에 담겨 마치 연결 리스트처럼 동작한다. 

해시가 검색을 빠르게 하는 정도는 알겠는데 그 과정까지는 모르거든. 그래서 위의 말이 잘 이해가안가! 자바에서 해시테이블, 버킷이 뭔지 거기서 연결리스트처럼 동작한다는게 무슨의미인지 잘 모르겠엉

**Comment by chldbtjd2272** [comment]
<img width="527" alt="스크린샷 2020-01-26 오전 1 10 49" src="https://user-images.githubusercontent.com/25260024/73123943-baf00780-3fd8-11ea-882a-cfa694ae0111.png">


해쉬 테이블은 키를 해쉬값으로 매핑하고 요 해쉬값을 주소삼아 데이터를 저장하는게 해쉬테이블이고 데이터가 저장되는 곳을 버킷이라고 해 근데 해쉬값이 같을경우가 있거든 32bit니까 겹칠수 있겠지 그럴경우 데이터가 저장된 버킷을 리스트로 만들고 다음주소와 데이터를 같이 저장시켜놓지 그래서 해쉬값이 하나로 몰릴경우 성능이 안좋아 질 수 밖에없는거야
