### ISSUE TITLE
[아이템 11] 지연초기화와 스레드의 관계

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#22]
> p.71, 필드를 지연초기화하려면 그 클래스를 스레드 안전하게 만들도록 신경써야한다.

솔직히 잘 모르겠습니다. 그 밑 11-4 예제도 이게 왜 스레드 안정성을 고려한 예시인지 모르겠어 !

**Comment by chldbtjd2272** [comment]
위에 예제는 스레드 안정성을 고려해야 하는 예시인거 같아. 스레드 안정성을 고려한 예시가 아니라.


지연 초기화 자체는 스레드 안정성을 고려하긴 해야해 
여러 스레드가 동시에 접근해서 초기화해 여러 객체가 생기지 않도록 방지해야하니까

class SomeClass {
  private Resource resource = null;
  public Resource getResource() {
    if (resource == null)
      resource = new Resource();
    return resource;
  }
}

예를 들어 위 코드는 new Resource()가 여러개가 생길 수 있겠지 그래서 syncronized키워드나 내부클래스를 사용하는 방식으로 지연초기화를 하면 스레드 안정성을 높혀 줄수있어

http://rpktech.com/2015/02/04/lazy-initialization-in-multi-threaded-environment/
