### ISSUE TITLE
[아이템 11] 적법한 hashCode 구현

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#23]
> p.68 11-1 code : 이 코드는 동치인 모든 객체에서 똑같은 해시코드를 반환하니 적법하다.

이거는 동치가 아닌 모든 객체도 똑같은 해시코드를 반환해서 뭔가,, 논리적 동치성자체가 안지켜질텐데 적법하다고해서 좀 말이 이상함 (나만 그렇게 생각하나 해서 올려봄)

**Comment by chldbtjd2272** [comment]
여기서 동치성을 만족하는 건 hashCode와는 관련없이 equals의 논리적 동치성이 같다는 걸 말하는거야
논리적 동치관계에서 항상 같은 해쉬값을 만족하니 
**두객체가 equals를 만족할때, 같은 해쉬값을 반환한다.**라는 조건을 만족시킬 수 있다는 거지.
이런 경우에 equals를 만족하지 않을때도 모두 같은 해쉬값을 반환하기때문에 해쉬품질이 안좋고 연결리스트를 조회하는 성능이 나오기 때문에 위와같은 코드는 사용하지말자는 내용이야
