### ISSUE TITLE
[2장] @EnableBatchProcessing

### ISSUE THREAD

**Issue by jyami-kim** [Java-Bom/ReadingRecord#239]
> @EnableBatchProcessing

질문 : 위 어노테이션 사용시 자동 설정되는 값들에 대해 공식문서로 한번 더 리마인드 하면 좋을 것 같아

**Comment by pci2676** [comment]
[Java docs](https://docs.spring.io/spring-batch/docs/2.2.x/apidocs/org/springframework/batch/core/configuration/annotation/EnableBatchProcessing.html)
> Note that only one of your configuration classes needs to have the @EnableBatchProcessing annotation. Once you have an @EnableBatchProcessing class in your configuration you will have an instance of StepScope so your beans inside steps can have @Scope("step"). You will also be able to @Autowired some useful stuff into your context:
a JobRepository (bean name "jobRepository")
a JobLauncher (bean name "jobLauncher")
a JobRegistry (bean name "jobRegistry")
a PlatformTransactionManager (bean name "transactionManager")
a JobBuilderFactory (bean name "jobBuilders") as a convenience to prevent you from having to inject the job repository into every job, as in the examples above
a StepBuilderFactory (bean name "stepBuilders") as a convenience to prevent you from having to inject the job repository and transaction manager into every step

[Spring Batch docs](https://docs.spring.io/spring-batch/docs/4.3.x/reference/html/job.html#javaConfig)

책에서도 나오지만 중요한 부분이니까!
