### ISSUE TITLE
[2장] 원격 청킹

### ISSUE THREAD

**Issue by NDjust** [Java-Bom/ReadingRecord#240]
> p.57 원격 청킹에 적합한 케이스

질문 : 원격 청킹에 적합한 시나리오로 `실제 처리에 비해 I/O 비용이 적은 시나리오`라고 책에는 적혀있는게 와닿는 예시가 잘 떠올르지 않아 예시 혹은 원격 청킹 동작방식 설명해주시면 감사드립니다!

**Comment by pci2676** [comment]
@NDjust 
원격 청킹의 동작방식은 이전 이슈에 답글로 달아뒀으니 넘어갈게요! 아래 이슈를 통해 확인해주세요!
https://github.com/Java-Bom/ReadingRecord/issues/238#issuecomment-932788311

>  원격 청킹에 적합한 시나리오로 실제 처리에 비해 I/O 비용이 적은 시나리오라고 책에는 적혀있는게

반대로 생각하면 I/O 비용이 큰 시나리오가 원격 청킹에 적합한 시나리오가 될 수 있을것 같네요.
Resource를 읽어서 파일로 쓰고 업로드해야하는 작업들이 어울릴것 같습니다.

예를 들면 
```
월말에 
해당 월의 일별 거래 내역 데이터를
일별로 파일로 쓰고 백업해야한다
```
는 요구사항이 있고 그 양이 많다면 사용할수 있지않을까요?

**Comment by NDjust** [comment]
@pci2676 님

> 원격 청킹에 적합한 시나리오로 실제 처리에 비해 I/O 비용이 적은 시나리오라고 책에는 적혀있는게

반대로 생각하면 I / O 처리 비용이 많은 시나리오가 적합하지 않다고 책에서 이야기 하고 있는데요! 
찬인님께서 동작방식 설명해주시는 거 보니, 원격청크는 미들웨어를 두고 `처리 요청 & 처리 결과 반환 및 기록`이라는 절차가 추가적으로 생겨 네트워크 비용이 발생해 I/O 처리가 많은 작업에 경우 부적합하다고 이해가 되네요:)

답변 감사합니다!
