### ISSUE TITLE
[2장] 파티셔닝

### ISSUE THREAD

**Issue by BangKiHyun** [Java-Bom/ReadingRecord#241]
> p.58 JobRepository가 복제된 작업이 없고 모든 작업이 완료됐음을 보장하기 때문에 내구성 있는 지속적인 통신이 필요없다.

질문 : 여기서 `내구성 있는 지속적인 통신이 필요없다`라는 말이 정확히 이해가 되지 않아서 질문드립니다!
제가 이해한 바로는 파티셔닝의 각 워커의 스텝이 독립적으로 동작하고 StepExecution을 별개로 갖기때문에 이를 통해 JopRepository에 데이터를 저장할 수 있게 되어서 지속적인 통신이 필요없다 라고 이해를 했는데 이해한 내용이 맞는지 궁금합니다.

**Comment by pci2676** [comment]
@BangKiHyun 
아래 이슈로 답변!
https://github.com/Java-Bom/ReadingRecord/issues/238#issuecomment-932788311
