### ISSUE TITLE
[아이템 11] 지연초기화 전략

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#25]
> p.71 해시코드를 지연초기화 하는 hashCode 메서드

아래 코드에서 왜 갑자기 if (result == 0) 이 나오는거구, 왜 갑자기 PhoneNumber 클래스에 hashCode 필드가 추가 된건지 모르겠음.
1. hashCode 가 0이 되면 안되나? (Null 을 표현하면 안되서 그런것 같긴함).
2. 왜 갑자기 hashCode 필드가 추가? (쓰레드 때문인가)
3. 그럼 PhoneNumber 클래스 초기화 할 때 맨처음에 멤버변수로 hashCode 라는 필드값도 임의적으로 생성해 줘야하는 것? 
4. 이렇게 하는 이유? (뭔가 쓰레드 때문일 것 같은데 긁적)

```java
private int hashCode

@Override public int hashCode(){
	int result = hashCode;
    if(result == 0){
    	result = Short.hashCode(areaCode);
    	...
    }
}
```

**Comment by mjung1798** [comment]
/다시 읽어보니까 지연초기화 설명 하려고 그렇게 만든건가 싶기도 하고

**Comment by chldbtjd2272** [comment]
지연 초기화 코드야
매번 해쉬를 계산하는게 부담되거나 hashCode가 자주 호출된다면 hashCode라는게 호출될 때 멤버변수에 hashCode에 캐쉬해놓도록 하려고 저렇게 만든거야.
result == 0인 경우는 hashCode가 한번도 호출이 안된경우 해쉬를 초기화 하려고 넣은 조건이고
