### ISSUE TITLE
[아이템 11] let 비용을 지불할만한 가치

### ISSUE THREAD

**Issue by jyami-kim** [Java-Bom/ReadingRecord#252]
> p.75 이 코드들은 디버그하기 어렵고, 경험이 적은 코틀린 개발자는 이해하기 어렵습니다. 따라서 비용이 발생합니다. 하지만 이 비용은 지불할 만한 가치가 있으므로 사용해도 괜찮습니다.

질문 : 코틀린이 안 익숙해서 그런가, 이런 코드를 짰을 때 어떤게 이득인지 바로 와닿지는 않아. 성능이 아니라 가독성에서 이득을 가진 키워드인건가?? let 키워드에 대한 이해가 부족한 것 같기도. let키워드가 가지는 이점이 궁금해

**Comment by chldbtjd2272** [comment]
let 키워드가 가독성에서 이점을 주는 경우

 - 연산을 아규먼트 처리 후로 이동시킬때
 ```kotlin
   print(students.filter{}.jointToString{}) 
   ->  students.filter{}.joinToString{}.let(::print)
 ```
 
 - 데코레이터를 사용해서 객체를 랩할때
```kotlin
FileInputStream("/file.gz")
        .let(::BufferedInputStream)
        .let(::ZipInputStream)
        .let(::ObjectInputStream)
        .readObject() as SomeObject 
```

let 키워드는 단순하게 비교하면 stream.map 과 비슷하다고 보면 될거같아
