### ISSUE TITLE
[아이템 13] Unit,Void,Nothing

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#253]
질문 : unit/void/nothing을 각각 어떤 의미로 사용해야하는지 설명 추가해주세요

**Comment by jyami-kim** [comment]
# Void

### 자바의 void

java.lang 패키지안에 있는 Void 클래스 : java의 primitive type인 void를 래핑하는 객체이다. (int wrapper인 Integer과 같다고 보면 된다.)

자바에서는 void 말고 Void를 리턴해야하는 경우가 많지 않다. : 제네릭에서 Void를 사용하는 정도의 용례

```java
package java.lang;

/**
 * The {@code Void} class is an uninstantiable placeholder class to hold a
 * reference to the {@code Class} object representing the Java keyword
 * void.
 *
 * @author  unascribed
 * @since   1.1
 */
public final
class Void {

    /**
     * The {@code Class} object representing the pseudo-type corresponding to
     * the keyword {@code void}.
     */
    @SuppressWarnings("unchecked")
    public static final Class<Void> TYPE = (Class<Void>) Class.getPrimitiveClass("void");

    /*
     * The Void class cannot be instantiated.
     */
    private Void() {}
}

```



### Void를 코틀린에서 사용할 때

```kotlin 
fun returnTypeAsVoidAttempt1() : Void {
    println("Trying with Void return type")
}
```

이때 컴파일이 되지 않는다.

```
Error: Kotlin: A 'return' expression required in a function with a block body ('{...}')
```

그래서 코틀린에서 Void 객체를 만들어서 return 해야하나. 위의 Void 클래스 정의와 같이 private constructor로 인스턴트화가 막혀있다.

따라서 위 경우에는 어쩔수 없이 Void를 nullable로 만들고 `Void?` null을 리턴해야한다.

```kotlin
fun returnTypeAsVoidAttempt1() : Void? {
    println("Trying with Void return type")
    return null
}
```



작동하는 솔루션이 있긴하나. java의 void와 같이 동일한 결과를 낼 수 있는 방법으로 Unit 타입이 있다. (의미 있는 것을 반환하지 않는 함수의 반환 유형)

https://www.baeldung.com/kotlin/void-type



# Unit

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unit/#unit

https://kotlinlang.org/docs/functions.html#unit-returning-functions

반환값이 필요없을 때, 함수의 반환타입으로 Unit을 사용한다.

반환타입이 Unit일 경우네는, `return Unit; `. `return;` 모두 선택적으로 작성해도 된다.

```kotlin
fun printHello(name: String?): Unit{
    if (name != null) {
        println("hello $name")
    } else {
        println("Hi")
    }
}
```

java에서의 void와 대응한다. 그러나 자바에서 void는 반환 값이 없음을 의미하는 특수 타입이지만, Unit은 class로 정의된 일반타입이다. 

Unit은 기본 반환 유형이므로 그리고 return 타입 명시를 안했을 때도 함수가 작동한다.

```kotlin
// Unit.kt
package kotlin

/**
 * The type with only one value: the `Unit` object. This type corresponds to the `void` type in Java.
 */
public object Unit {
    override fun toString() = "kotlin.Unit"
}

```

따라서 Unit 타입을 반환하는 함수는 return을 생략해도 암묵적으로 Unit 타입 객체를 리턴한다 (싱글턴 객체이므로 객체 생성은 하지 않는다.)



# Nothing

kotlin에서는 throw가 expression 이다. 그래서 이때 throw의 타입이 `Nothing` 이다.

이 타입은 값이 없으며, 도달할 수 없는 코드 위치를 표한하는데 사용된다. Nothing을 사용하면, 도달할 수 없는 코드의 위치를 컴파일단에서 체크가 가능하다.

```kotlin
fun fail(message: String): Nothing {
    throw IllegalArgumentException(message)
}
```

컴파일단 체크 덕분에 잠재적인 버그와 좋지 않은 코드로부터 확인이 가능하다. 반환 유형이 Nothing인 함수가 호출되면 이 함수 호출 이상으로 실행되지 않고, 컴파일러에서 경고를 내보낸다. 

```kotlin
fun invokeANothingOnlyFunction() {
    fail("nothing")
		println("hello") // Unreachable code
}
```



또한 Nothing은 type inference (타입추론)에도 사용이 가능하다.

- null을 사용하여 초기화된 값일 때의 타입추론
- 구체적인 타입을 결정하는데 사용할 수 없는 경우에서의 타입추론

```kotlin 
val x = null // "type : Nothing?"
val l = listOf(null) // "type : List<Nothing?>"
```

Nothing은 java에서 대응되는 개념이 없으며, 자바에서는 주로 throw 처리를 할 때 void를 사용했었다. 



```kotlin
// Nothing.kt
package kotlin

/**
 * Nothing has no instances. You can use Nothing to represent "a value that never exists": for example,
 * if a function has the return type of Nothing, it means that it never returns (always throws an exception).
 */
public class Nothing private constructor()

```

마찬가지로 Nothing도 객체를 생성할 수 없다. (값을 가지지 않는다.)

따라서 Nothing이 값을 가질 수 있는 경우는 Nothing? 에서 null 이 할당되었을 때 뿐이다.
