### ISSUE TITLE
[아이템 23] 타입 파라미터

### ISSUE THREAD

**Issue by NDjust** [Java-Bom/ReadingRecord#256]
> p.134 이렇게 코드를 작성하면, Forest와 addTree의 타입 파라미터가 독립적으로 동작합니다.
```kotlin
interface Tree
class Birch: Tree
class Spruce: Tree

class Forest<T: Tree> {
    fun <T: Tree> addTree(tree: T) {
        // ....
    }
}
```

질문 : 왜 독립적으로 동작하는 자세하게 설명 부탁드리겠습니다!

**Comment by Gobukgol** [comment]
타입 파라미터가 어떤건지 찾는 것은 자신의 스코프에서 가장 가까운 것을 찾는 것이라고 보면 될 것 같아.

![image](https://user-images.githubusercontent.com/34976178/168414501-25339953-5a41-4972-9238-a9fe71b42a48.png)

이렇게 IDE 에서도 함수에 명시되어있는 타입파라미터를 참조하고 있다고 표시해주고있고.
독립적으로 동작한다는 의미는 가장 가까운 타입 파라미터를 참조하기 때문에 위의 코드에서는 Class에 정의된 타입을 쓰지않고 함수에 타입을 쓰고있어서  독립적으로 동작한다고 보면 좋을 것 같아.
