### ISSUE TITLE
[아이템11] 지연초기화 hashcode 메소드

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#27]
> pg. 71 코드 11-4 

코드 11-4에서 지연 초기화 전략 hashcode 메소드에서 어떤 부분이 스레드 안정성을 고려한 부분인지 잘 이해가 안돼

**Comment by chldbtjd2272** [comment]
https://github.com/Java-Bom/ReadingRecord/issues/22
