### ISSUE TITLE
[아이템11] 해쉬테이블이 연결리스트 처럼 동작하는 것

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#28]
> pg.68 코드11-1 최악의 hashCode 구현

저거 관련해서 찾아보니까 저런 상황을 해쉬충돌이라고 하더라구 그런데 그걸 해결하는 방법 중하나가 체이닝이라고해서 해쉬값이 같을 경우 연결리스트로 만들어서 해쉬충돌을 해결한다고 나와있는데, 그렇다면 책에서 나온 '해쉬테이블이 연결리스트 처럼 동작한다' 라는 말이 결국 자바의 HashMap이 체이닝으로 해결하도록 구현 되어 있는 거야?

**Comment by chldbtjd2272** [comment]
맞아 해쉬충돌이 일어나면 처음 저장되어 있는 노드에 다음 노드의 주소를 새기고 그 다음 노드에 값을 저장해놔
그래서 그 해쉬를 조회했을때 처음노드에 값을보고 아니다 싶으면 다음노드로 가서 확인하도록 구현되어져있어
