### ISSUE TITLE
[아이템 13] unchecked exception

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#29]
> p 80 : CloneNotSupported Exception이 사실은 비검사 예외(unchecked exception)였어야 했다는신호다.

문맥으로 unchecked exception 은 try catch로 해당 메서드에서 에러를 잡는걸로 이해했구, checked exception은 method에서 throw를 던지는거라고 이해를 했는데 맞나여?! 그리고 코드를 보고싶음!

**Comment by Gobukgol** [comment]
unchecked exception하고 checked exception은 Runtime Exception이냐 아니냐로 구분할 수 있는데 unchecked exception은 Runtime Exception을 상속받는 예외들을 얘기하고 checked Exception의 경우 반드시 예외 처리를 해야한다고 unchecked exception은 NullPointerException같이 명시적으로 예외처리를 하지않아도 되는 경우라고해. 

그런데 CloneNotSupportedException의 경우 clone을 재정의한 클래스가 Cloneable을 상속받지 않았을 때 발생하는 예외이고 이 경우는 개발자가 의도적으로 하위 클래스의 clone 재정의를 막는다던가 실수로 Cloneable을 상속받지 않았을 때니깐 unchecked exception에 어울리는 예외인데 Java에서는 해당 Exception을 checked exception으로 설계하였으니 ''비검사 예외였어야 했다''라고 얘기한다고 생각해.

![image](https://user-images.githubusercontent.com/34976178/73598493-3c690c00-457c-11ea-819f-a0334ce2de66.png)
그리고 이렇게 thows로 예외처리를 clone을 호출한 메소드에서 처리하게 하지않고
![image](https://user-images.githubusercontent.com/34976178/73598496-47bc3780-457c-11ea-9eaa-b4adb5a63bbe.png)
clone 메소드 내부에서 try-catch 로 예외처리를 해서 clone을 호출하는 메소드가 checked exception처리를 안하도록 해야해
