### ISSUE TITLE
[아이템 13] Arrays.copyOf

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#30]
> 80p : Stack class code

이 주제랑은 무관한 이야기이긴한데, 여기서 "// 원소를 위한 공간을 적어도 하나 이상 확보한다" 라는 말이있는데, 

Arrays.copyOf(elements, 2*size + 1); 여기서 2를 왜 곱한거야? 

원소를 위한 공간을 적어도 하나 이상 확보하는거면 size + 1  아닌가?? 뭔가 아니면 자료형에 따른 byte 때문인가 싶기도하고!

**Comment by Gobukgol** [comment]
음... 나는 size + 1 을 하면 배열의 크기가 기존에서 1만큼만 늘어나니까 push를 여러번 하게되면 배열 복사를 매번하니까 성능을 위해서 크게 늘려준게 아닐까 생각했어.
