### ISSUE TITLE
[아이템 13] 생성자 호출

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#31]
> p 81 : Stack 클래스의 하나뿐인 생성자를 호출한다면 이러한 상황은 절대 일어나지 않는다.

나 맥락 이해가 안되서ㅠㅜㅠ 다들 어떻게 독해했는지 궁금함

**Comment by Gobukgol** [comment]
Object의 clone 메소드는 객체의 필드를 복사할때 값을 새로 생성한다기 보단 쉽게 생각했을때 각 필드를 '='를 이용해서 복사한다고 생각하면 좋을것 같아. 그래서 예제 코드의 생성자가 호출되지 않고 복사가 되서 각각의 elements는 같은 인스턴스를 보고있게되는거야.
![image](https://user-images.githubusercontent.com/34976178/73598067-d1690680-4576-11ea-9efb-25ef220e3c84.png)
![image](https://user-images.githubusercontent.com/34976178/73598069-d3cb6080-4576-11ea-8179-3f185986bbd5.png)
실제로 super.clone으로만 Stack 의 clone을 재정의 했을때 stack.clone()을 했음에도 불구하고 stack의 생성자는 한번 밖에 호출되지 않더라구
