### ISSUE TITLE
[아이템 13] 고수준 API를 활용한 복사

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#34]
p 84 
bukets 필드를 새로운 버킷배열로 초기화 하고 원본테이블에 담긴 모든 키 값 쌍 각각에 대해 복제본 테이블의 put메서드를 호출해 둘의 내용이 똑같게 해주면 된다.

요부분이 왜 앞부분보다 느린지, Cloneable 아키텍처의 필드단위 객체복사는 뭔지 설명해줘

**Comment by Gobukgol** [comment]
Cloneable 아키텍처의 필드 단위 객체 복사는 클론의 대상이 되는 객체의 모든 필드를 기준으로 해서 객체를 복사하는 방식인데 쉽게 생각해서 '='을 이용해서 필드를 복사한다고 보면 될것같아. 그래서 책 예제 코드같이 하나씩 객체들을 새로 생성해서 복사하는 것이 기존의 clone으로 복사하는 것 보다는 속도가 느린 이유라고 생각해.

추가로 객체 배열을 clone으로 복사 했을 때, 새로 생긴 배열의 주소값은 다른 반면에 배열의 원소는 같은 주소값을 가지고 있어.
![image](https://user-images.githubusercontent.com/34976178/73597511-12115180-4570-11ea-8b13-e7fc9ce5fa78.png)
![image](https://user-images.githubusercontent.com/34976178/73597520-1dfd1380-4570-11ea-95c9-58189da2ad2e.png)
