### ISSUE TITLE
[아이템 13] 믹스인 인터페이스

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#35]
> p.77 Cloneable은 복제해도 되는 클래스임을 명시하는 용도의 믹스인 인터페이스지만,

믹스인 인터페이스가 뭘 말하는거고 Cloneable 인터페이스가 왜 믹스인 인터페이스인지! 찾아봤는데 명확히 모르겠다 ㅠㅠ

**Comment by Gobukgol** [comment]
믹스인은 클래스가 본인의 기능 이외에 추가로 구현할 수 있는 자료형으로, 어떤 선택적 기능을 제공한다는 사실을 선언하기 위해 쓰여. 예를들어 Comparable을 구현한 클래스는 그 클래스가 다른 객체와 비교 가능함을 선언하는 것이고 Cloneable의 같은 경우도 Cloneable을 상속받은 클래스는 clone() 함수를 사용할 수 있다는 것을 알려주는 거겠지?
