### ISSUE TITLE
[아이템 13] clone 메서드에서는 재정의 될 수 있는 메서드르 호출해서는 안된다

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#36]
> p.84, 만약 clone이 하위 클래스에서 재정의한 메서드를 호출하면, 하위 클래스는 복제 과정에서 자신의 상태를 교정할 기회를 잃게되어 원본과 복제본의 상태가 달라질 가능성이 크다.

이 문단 통으로 이해가 안가 ㅠ! 예제랑 같이 보여주면 좋을것같아

**Comment by Gobukgol** [comment]
```java
public class Sup implements Cloneable{
    String type;

    public Sup() {
        this.type = "super";
    }

    public void overrideMe() {
        System.out.println("super method");
    }

    @Override
    public Sup clone() {
        try {
            overrideMe();
            return (Sup) super.clone();
        } catch (CloneNotSupportedException e) {
            throw new RuntimeException();
        }
    }
}

public class Sub extends Sup {
    String temp;
    @Override
    public void overrideMe() {
        System.out.println("sub mehtod");
        System.out.println(temp);
        type = "sub";
    }

    @Override
    public Sub clone() {
        Sub clone = (Sub) super.clone();
        clone.temp = "temp";
        return clone;
    }

}
```


[아이템19] 코드를 참조해서 구현해봤어. 하위 클래스에서 재정의 될 수 있는 메소드를 상위 클래스의 clone 메소드에서 호출하면 하위 클래스의 재정의 된 메소드가 실행되기때문에 문제가 생길 수 있어. Sub 객체를 생성하고 clone했을때 overrideMe 메소드가 상위 클래스인 Sup의 clone에서 호출하고 있더라도 Sub 객체의 overrideMe 메소드가 호출되어서 기존 Sub 객체의 값이 변하고 String temp 필드에 값이 할당되기 전에 출력해서 null이 출력돼

![image](https://user-images.githubusercontent.com/34976178/74046913-cd276800-4a12-11ea-8e7a-5ff57c4aff30.png)
