### ISSUE TITLE
[아이템 3] transient가 역직렬화시 새로운 인스턴스 생성을 방지하는 이유

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#4]
24p
> 클래스의 인스턴스 필드를 transient로 선언하고 readResolve 메서드를 제공해야 한다.

transient가 직렬화시 제외시켜주는 건 알겠는데, 이게 왜 인스턴스를 새로 생성하지 않는다는걸 보장하는지 잘 모르겠음...

**Comment by csbsjy** [comment]
직렬화한 클래스를 역직렬화할 때 인스턴스를 새로 만들어 반환하는 메서드가 readResolve 메서드인걸로 알고있어. 해당 문장은 직렬화/역직렬화 시 새로운 인스턴스를 생성하지 않도록 반환하기 위해서는 "직렬화를 제외하는 transient 선언 + 역직렬화 시 인스턴스를 새로 만들어 반환하지 않고 싱글턴 인스턴스를 반환하도록 readResolve 메서드를 구현하여 처리" 하라는 문장으로 이해했어 !

**Comment by csbsjy** [comment]
다시 찾아보다가 이전에 달았던 답변이 엉뚱한 답변이었던거 깨달아서 다시 달러왔엉. 싱글턴 객체 만드는 코드를 완전 생각 안했었다 ㅠㅠ 나는 아래 코드로 테스트했고

```java
package com.jy.effectivejava;

import java.io.Serializable;

public class SingletonObject implements Serializable {
    public static final SingletonObject INSTANCE = new SingletonObject();
//    transient public static final SingletonObject INSTANCE = new SingletonObject();

    private SingletonObject() {
        System.out.println("Constructor");
    }
/*
    public Object readResolve(){
        return this.INSTANCE;
    }*/
}
```
역직렬화는 기본 생성자를 호출하지 않고 값을 복사해서 인스턴스를 반환해. 그때 통하는게 readResolve() 메서드야. 숨겨진 생성자가 있다는데 이거는 찾아도 잘 안나오네 ㅠㅠ 그래서 위의 주석달린 코드대로 직렬화 > 역직렬화를 수행하면 Constructor 메시지는 직렬화 할 때 한번 출력되고 역직렬화 때는 출력되지 않지만 객체값을 비교해보면 다른 객체로 나와. 

transient 는 정확하게 말하면 필드의 상태값을 전송하지 않는다는 키워드인데 여기서는 INSTANCE 의 상태값인 new SingletonObject() 를 의미해. 그래서 언뜻 보면 new SingletonObject() 만 전송하지 않으면 싱글턴을 유지하고 역직렬화 할 수 있지 않을까 생각이 들 수 있어서 언급된것같아. 근데 실제로 해보면 transient 안붙이고 readResolve 주석만 풀어도 싱글턴이 유지되는거를 확인할 수 있는데, 위에서 말했다시피 역직렬화 시 반환되는 인스턴스를 관장하는애는 readResolve 메서드이기 때문이야. transient 를 붙이라고하는이유는 그냥 이건 내 생각인데 어차피 안쓰일 상태값을 굳이 전달할 필요가 없어서 일것같은데 확실하게는 모르겠어 ㅋㅋㅋ 다른 이유가 있을지도.. 

결론은 transient 키워드가 중요한게아니라 readResolve 에서 INSTANCE 를 반환하는게 새로운 인스턴스 생성을 방지하는것이다 ~~

**Comment by csbsjy** [comment]
코드 올리기

**Comment by mjung1798** [comment]
https://github.com/Java-Bom/ReadingRecord/issues/163
