### ISSUE TITLE
[아이템14] 해쉬코드를 이용한 compare

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#41]
> Pg94. 해쉬코드를 이용한 compare 방식 

만약 두 객체가 논리적으로 동치가 아닌데 해쉬코드는 같은 경우가 있을 수 있잖아 이런 경우에는 해쉬코드를 이용해서 compare를 구현하지않는게 맞는거야?

**Comment by pci2676** [comment]
확신을 가지고 답변은 할수 없지만,

생각해 봤을때 hashCode로 변환하는 순간 int의 범위 안에 들어가기 때문에 겹칠수 있는 위험이 있으니까 그리 좋지 않은 구현이라고 생각이 돼.
compareTo를 구현하는건 Comparable을 구현한 객체들의 순서를 비교하고 싶은게 가장 큰 목적인데
hashCode를 이용하면 필드간의 우선순위가 무시되기 때문에 적절한 구현이라고 볼 수 없는것 같아.

따라서 책에서 hashCode를 예로 든건 값의 차로 인한 오류가 생길수 있다는걸 보여주기 위한 단적인 예라고 생각이 돼.

**Comment by pci2676** [comment]
```java
    @DisplayName("hashCode 를 이용할 경우 필드간의 우선순위 비교가 불가능해 진다.")
    @Test
    void compareTo() {
        // 두 객체 모두 hash 값이 1024로 같다.
        HashObject hashObject1 = new HashObject(1, 32);
        HashObject hashObject2 = new HashObject(2, 1);
        assertThat(hashObject1.hashCode() == 1024).isEqualTo(hashObject2.hashCode() == 1024);
        assertThat(hashObject1.compareTo(hashObject2)).isEqualTo(0);
    }
```
![image](https://user-images.githubusercontent.com/13347548/74025163-afdca480-49e6-11ea-9eab-ee56bee6aa0e.png)
