### ISSUE TITLE
[아이템 16] private 중첩 클래스

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#42]
> pg.103 하지만 package-private 클래스 혹은 private 중첩 클래스라면 데이터 필드를 노출한다 해도 하등의 문제가 없다.....

위에 언급된 말이 포함된 문단을 이해하기 어렵네... 간단한 예제 보여줄 수 있을까?

**Comment by csbsjy** [comment]
![image](https://user-images.githubusercontent.com/47847993/74445109-34349900-4eb9-11ea-9c85-6d1ac1419e4e.png)
![image](https://user-images.githubusercontent.com/47847993/74445174-4ca4b380-4eb9-11ea-9ba1-4bd493c8f63d.png)


package-private 상황에서 보자.

문단이 좀 길어서 나눠서 보면,
>  클래스 선언 면에서나 이를 사용하는 코드 면에서 접근자 방식보다 훨씬 깔끔하다.
: Getter, Setter 없으니까 깔끔하지
> 클라이언트 코드가 클래스 내부 표현에 묶이기는 하나, 클라이언트도 어차피 이 클래스를 포함하는 패키지 안에서만 동작하는 코드이다. 
: 이 경우에서라면 package-private 한 클래스 Product가 cost 이라는 필드 이름을 바꾸고싶다고해보자. 그럼 Client 클래스의 buyProduct 의 if문, balance -= product.cost 를 그 필드이름을 바꾸어야겠지? 타입이 변한다면 더 복잡해질거고. 이렇게 직접 이름으로 가져다 쓰기 때문에 내부표현에 묶이지만 어쨋든 이 패키지 내부의 클래스들만 수정하면 되기때문에 그래도 ㅇㅋ라는 뜻같아. 
> private 중첩 클래스의 경우라면 수정범위가 더 좁아져서 이 클래스를 포함하는 외부 클래스까지로 제한된다. 
: private 중첩 클래스의 필드는 어차피 그 클래스를 포함하는 톱레벨 클래스에서만 접근가능하기 때문에 package-private 보다 더 수정할게 없어진다~
