### ISSUE TITLE
[아이템 15] 리스코프 치환원칙

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#43]
> p 98 : 그런데 멤버 접근성을 좁히지 못하게 방해하는 제약이 있다. 상위클래스의 메서드를 재정의할 때는 그 접근 수준을 상위 클래스에서 보다 좁게 설정할 수 없다.

부모에서 public calc() 라는 메서드가 있으면 자식에서는 private calc() 처럼 오버라이딩이 안된다는 소리야??

**Comment by csbsjy** [comment]
컴파일에러나서 예제도 못짜는군 ..!  웅웅 접근제어자가 다르면 오버라이딩 자체가 컴파일 에러나는데, 그 이유가 리스코프 치환원칙을 위반하기 때문이라는거같아! public 메서드 calc 를 제공했던 부모클래스가 자식클래스로 치환되면서 갑자기 외부에서 사용할 수 없게되면 안되니까?
