### ISSUE TITLE
[아이템 15] 모듈 시스템

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#44]
> 100 p : 자바 9에서는 모듈시스템이라는 개념이 도입되면서 두가지 암묵적 접근 수준이 추가되었다.

아예 처음 본거라서 혹시 예제 코드 가능한가요?!

**Comment by mjung1798** [comment]
> 101 p : 모듈 안으로 부터 (모듈 시스템을 적용하지 않는) 일반 패키지로의 접근에 특별한 조치를 취해야한다.

모듈안 코드에서 다른 일반 클래스에 접근한다는거..? 맥락 이해가 잘 안되여

**Comment by csbsjy** [comment]
이거 신기하당 ㅋㅋ 근데 내가 멀티모듈 익숙치 않아서 잘 모르겠지만 멀티모듈 프로젝트를 더 쉽게 구성하게해주는? 그런거같아. 첫번째 글 의미는 모듈 안에서 public으로 백날 열어줘도 외부 모듈에서는 사용할 수 없기 때문에  <u>외부에 공개하지 않으면서도 같은 모률을 이루는 패키지 사이에서는 자유롭게 공유할 수 있다.</u> 말이 나온거같아. 복잡해보이는데 우리 멀티모듈 구성했던거랑 똑같은..듯? 

**패키지 구조**
![image](https://user-images.githubusercontent.com/47847993/74583194-f5612900-5007-11ea-8f31-fbfe3025a0d1.png)

간단하게 parser 모듈을 service 모듈이 사용해야 하는 상황이야! 
![image](https://user-images.githubusercontent.com/47847993/74583208-1cb7f600-5008-11ea-97a5-f3525fddcee2.png)

Bomparser 는 public 클래스임에도 외부 모듈인 BomService 에서 사용하지 못해!  근데 그렇게 그래들 설정 안해줘도 
![image](https://user-images.githubusercontent.com/47847993/74583216-35281080-5008-11ea-8a68-3897cd7b7605.png)


아래처럼 parser 모듈의 module-info.java에 export 설정하고 service 에 requires 를 추가하면 
![image](https://user-images.githubusercontent.com/47847993/74583232-60126480-5008-11ea-890d-48937b3b94fe.png)
![image](https://user-images.githubusercontent.com/47847993/74583359-a5836180-5009-11ea-8411-fb7eddb90182.png)


아래처럼 BomParser 사용이 가능합니다
![image](https://user-images.githubusercontent.com/47847993/74583246-90f29980-5008-11ea-985e-a4f1b1a0b92a.png)

**Comment by csbsjy** [comment]
두번째꺼는 https://stackoverflow.com/questions/48365299/calling-a-non-module-class-from-a-module-class-in-java-9#comment83717691_48365299 이 글이 딱 그 글인거같아. 모듈에서 모듈이 아닌 클래스를 사용하려면 컴파일할때 새로운 조치가 필요한가봐~~~ --add-modules moduleC=ALL-UNNAMED 라는 옵션을 줘야하는듯??
