### ISSUE TITLE
[아이템16] 불변필드 노출 p103

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#46]
불변필드를 노출하면 api를 변경하지 않고는 표현방식을 바꿀 수 없고, 필드를 읽을때 부수작업이 생긴다는게 무슨의미인지??

**Comment by csbsjy** [comment]
필드를 읽을 때 부수작업을 할 수 없다는 의미였어! 이건 foo.name 이런식으로 읽어오게되잖아. 만약 접근자를 사용하면 그 메서드 안에서 부수작업을 할 수 있는데 이 경우에는 불가해져. 그리고 앞에 질문은 나는 public한 필드를 api처럼 이해했어. 함수사용할 때처럼 사용하니까.. 그래서 필드 명이 바뀌면 에이피에이 명도 바뀌고 등등..
