### ISSUE TITLE
[아이템 17] 다단계 연산, 가변 동반클래스

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#47]
> p. 110 첫 번째는 흔히 쓰일 다단계 연산들을 예측하여 ~ 그 어려운 부분들을 모두 BigInteger가 대신 처리해주니 말이다. 문단

다단계 연산, 가변 동반 클래스에 대한 개념을 아예 몰라서 이해가 전혀 안돼 ㅠ ㅠ 
간단한 개념 설명 기반으로 이 문단 내용 알려주면 좋겠어용

**Comment by mjung1798** [comment]
**다단계 연산** : multi-step operation : 단계를 갖고 이루어지는 연산
예시 ) 모듈러 지수 연산

**가변 동반 클래스** : http://happinessoncode.com/2017/04/19/java8-changes-in-interface/
출처: https://sjh836.tistory.com/170 [빨간색코딩]
객체를 완성하기까지 단계가 많고, 중간 단계의 객체들이 모두 버려지면 성능문제가 생길 수 있다.
해결방법으로는 다단계 연산을 기본으로 제공하는 것이다. 가변 동반 클래스라고 한다. (불변클래스인 String으로 예를들자면, StringBuilder, StringBuffer이 있다)

BigInteger의 ) private static class UnsafeHolder {} 클래스

**Comment by mjung1798** [comment]
BigInteger의 ) private static class UnsafeHolder {} 클래스
BigInteger의 ) BigInteger() 클래스 (packate-private으로 이루어져있음)

**Comment by mjung1798** [comment]
BigInteger의 내부 패키지를 보면
![image](https://user-images.githubusercontent.com/26458200/75087090-762ba200-557f-11ea-9144-91364ce28652.png)
BitSieve
SignedMutableBigInteger
MutableBigInteger
이 클래스가 package-private으로 되어있는 가변 동반 클래스이다. 
BigInteger의 내부 연산을 빠르게 하기 위한 클래스로 사용되며, 모듈러 지수 연산과 같은 복잡한 연산을 빠르게 하기 위한 클래스로 사용된다.
