### ISSUE TITLE
[아이템 17] 재정의 가능한 클래스의 위험성(BigInteger)

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#48]
> p. 111 이 값들이 불변이어야 클래스의 보안을 지킬 수 있다면 진짜 인지 확인해야한다. 그렇지 않으면 방어적 복사를 수행해야 한다. 

비슷한 내용이 반복해서 나오는데 사실 아직도 "재정의" 가능한 클래스가 보안 측면에서 어떤 위험성이 있는지 모르겠어. 그동안은 직렬화, 역직렬화 과정에서 문제가 있을 수 있겠다고 어렴풋이 생각했는데 BigInteger 예시는 직렬화, 역직렬화랑은 전혀 관계없는 것 같아서 ..! 재정의 가능한 클래스가 어떤식으로 보안에 위험을 끼칠 수 있는지 예제가있으면 좋을 것 같앙

**Comment by mjung1798** [comment]
```java
public class BigBigInteger extends BigInteger {
    // BigInteger 하위 호환성으로 인한 보안 문제
```
이런식으로 상속을 이용해서 BigBigInteger 클래스가 나오고, 이 클래스의 구현을 한 클라이언트가 이 객체를 불변으로 사용하지 않았을 경우에 문제가 생긴다는 거 같아.

불변으로 만들지 않아서, Thread safe한 객체가 아닌데, 부모 타입인 BigInteger로 return이 가능하니까, 이게 재정의 된 객체인지 모르고 Thread를 불변객체라 생각하고 사용한다면 문제가 생기겠지.

그래서 진짜  BigInteger인지 확인하라고 하는 이유인것 같아. 아래 코드가 예시

```java
        BigInteger bigInteger = new BigBigInteger("1234");
        assertThat(bigInteger.getClass()).isNotEqualTo(BigInteger.class);
```
