### ISSUE TITLE
[아이템 17] StringBuilder와 StringBuffer

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#50]
> pg.110 StringBuilder(와 구닥다리 전임자 StringBuffer)다. 
에서 왜 StringBuffer가 StringBuilder의 구닥다리 전임자라고 하는지 이유가 궁금해!

**Comment by mjung1798** [comment]
구닥다리 전임자라고 하는건 정말 StringBuffer가 더 먼저 나와서 그런거 아닐까ㅋㅋㅋ
StringBuffer : java 1.0 : https://docs.oracle.com/javase/8/docs/api/java/lang/StringBuffer.html
StringBuilder : java 1.5 : https://docs.oracle.com/javase/8/docs/api/java/lang/StringBuilder.html

----
StringBuffer와 StringBuilder 는 기능이 동일하지만 한 가지 차이점이 존재합니다. 바로 동기화 처리 문제입니다.
StringBuffer 는 동기화(synchronization)를 지원하여 멀티 스레드 환경에서 안전하게 동작하지만 StringBuilder 는 동기화를 지원하지 않습니다. 따라서 단일 스레드 환경에서는 StringBuilder 를, 멀티 스레드 환경에서는 StringBuilder를 사용하는 것이 권장됩니다. 굳이 두 클래스의 성능을 비교하자면 단일 스레드 환경에서 StringBuilder 가 StringBuffer 보다 빠르게 동작합니다.

단일스레드환경에서 StringBuffer를 사용한다고 문제가 되는 것은 아니지만, 동기화 관련 처리로 인해 StringBuilder에 비해 성능이 좋지 않습니다.

단순한 성능만 놓고 본다면 연산이 많은 경우

StringBuilder > StringBuffer >>> String

정도로 보시면 되겠습니다.

하지만 각 문자열 클래스들은 성능 이슈 외에도 사용 편의성, 멀티스레드 환경 등 여러가지 고려해야할 요인이 있으므로 이에 적합한 것을 사용하면 될 것입니다.

출처: https://ooz.co.kr/298 [이러쿵저러쿵]
