### ISSUE TITLE
[아이템 17] 성능을 위해 다음처럼 살짝 완화할 수 있다.

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#51]
> p.111~112 어떤 불변 클래스는 계산 비용이 큰 값을 나중에 (처음 쓰일 때) 계산하여 final이 아닌 필드에 캐시 해놓기도 한다.

예전에 `hashCode` 때 처럼 캐싱하는거 말하는거같은데 예시 코드 있으면 좋을거 같아!

**Comment by mjung1798** [comment]
String.class 에 있는 hash 필드가 있는 것 같습니다

![image](https://user-images.githubusercontent.com/26458200/75084671-dd882880-5564-11ea-90b4-aa29d6a8cba5.png)
흠,, 근데 캐시 과정이 내부에서 어떻게 일어나는지는 모르겠네, 
코드 까보니까 hash를 저장하고, 사용하는 곳이 hashCode() override에서만 사용해.
