### ISSUE TITLE
[아이템 18] SELF 문제

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#52]
> p. 119, 래퍼클래스는 콜백 프레임워크에서 자기 자신의 참조를 ~ 이를 SELF 문제라고 한다.

"내부 객체는 자신을 감싸고 있는 래퍼의 존재를 모르니" 이 부분 이해가 안가.
내부객체가 정확히 뭘 말하는지도 잘 모르겠다 ㅠㅠ SELF 문제에 대해 설명해주면 좋겠어욤!

**Comment by csbsjy** [comment]
스택오버플로우도 같이 설명해주면 감사하겠습니다~

**Comment by mjung1798** [comment]
스택오버플로우 : https://stackoverflow.com/questions/28254116/wrapper-classes-are-not-suited-for-callback-frameworks

**Comment by mjung1798** [comment]
wrapping된 this를 알 수 있는 방법이 js에는 있지만, java에서는 없다.
내부 클래스를 짜는 시점에는 알 수 없음.

**Comment by mjung1798** [comment]
https://github.com/Java-Bom/ReadingRecord/tree/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%20%EC%9E%90%EB%B0%94/effectiveJava/src/main/java/item18/callbackExample

selfProblemTest.js와 callbackJava 폴더안에 있는 내용 참고하세요 :)

javascript에서는 bind를 이용해 콜백엔에서 사용되는 this 객체를 바깥 객체 (Wrapper 객체)로 바꿀 수 있지만,

Java에서는 bind와 같은 기능을 하지못하며, this가 가리키는 것은 무조껀 Wrapped된 객체 입니다.

bind() 메소드는 바로 실행되는 것이 아니라 설정을 저장하는 것 -> this 객체가 바뀔 수 있다.
주로 callback 함수에서 많이 쓰인다.
