### ISSUE TITLE
[아이템 19] private 도우미클래스

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#54]
> p. 128, 클래스의 동작을 유지하면서 재정의 가능 메서드를 사용하는 코드를 제거할 수 있는 방법. private 도웅미 메서드를 사용하라.

예제좀! 이해가 안갑니당

**Comment by Gobukgol** [comment]
```java
public class Super {
    public Super() {
//      overrideMe();
        helpMethod();
    }

    public void overrideMe() {
        helpMethod();
    }

    //도우미 메소드
    private void helpMethod() {
        System.out.println("super method");
    }
}
public class Sub extends Super{
    private String str;
    public Sub() {
        str = "Sub String";
    }

    @Override
    public void overrideMe() {
        System.out.println(str);
    }


    public static void main(String[] args) {
        Sub sub = new Sub();
        sub.overrideMe();
    }
}
```
![image](https://user-images.githubusercontent.com/34976178/75440561-57724480-599f-11ea-95b3-faeeb3294a48.png)

책에 나와있는 생성자 관련 코드를 조금 수정해봤어. 이 예시가 정확하게 맞는진 모르겠는데, 재정의 가능한 메소드인 overrideMe 메소드가 하는 일을 도우미 메소드인 helpMethod로 옮기고 overrideMe 메소드가 helpMethod 메소드를 호출하도록 변경했어. 문제가 생기는 코드에선 재정의 가능한 메소드를 바로 호출했는데 지금은 helpMethod 메소드를 호출하도록 바꾸었어.
실행 결과 이전에는 상위 클래스의 생성자가 하위 클래스에서 재정의된 메소드를 호출해서 초기화 되지않은 인스턴스 필드를 참조해서 null값이 출력되는 일이 지금은 발생하지 않고 정상적으로 동작했어. 또 하위 클래스에서 재정의한 메소드가 본인의 역할을 제대로 수행을 해.
