### ISSUE TITLE
[아이템 19] 재정의 가능 메서드를 사용하지 않게

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#57]
> 128p. 재정의 가능 메서드를 사용하지 않게 만들고 이 사실을 문서로 남기는 것이다.

이거 public 메서드를 사용하지 말라는 뜻인가?

**Comment by Gobukgol** [comment]
간단하게 보면 그런 의미가 맞는것 같아. 상위 클래스의 A 메소드가 재정의 가능한 B메소드를 호출하는 경우에 하위 클래스가 B메소드를 재정의하고 A메소드를 호출하면 A의 기능이 개발자가 의도한대로 흘러가지 않을 경우가 생기니까 문제가 될 수 있다고 책에서 얘기하고 있고. 그런 재정의 가능한 것들은 public이고 final이 아닐때라고 볼 수 있을 것 같아.
