### ISSUE TITLE
[아이템 20] 믹스인

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#58]
> 130p. 인터페이스는 믹스인 정의에 안성맞춤이다. 믹스인이란 클래스가 구현할 수 있는 타입으로...

믹스인 검색해보니까 javascript만 나옴ㅠㅠ 자바예제 부탁해요

그냥 여러개를 계속 인터페이스 상속받을 수 있으니 섞어쓸 수 있다는건가 싶기도 하네여

**Comment by Gobukgol** [comment]
음 저번에도 믹스인 얘기가 나왔었는데 쉽게 생각하면 믹스인 인터페이스는 어떤 클래스가 믹스인 인터페이스를 상속받고 구현하면 본인의 일 외에도 추가적으로 믹스인 인터페이스가 제공하는 기능을 할 수 있다. 라고 생각하면 좋을것 같아. 책 예제에서 같이 Comparable을 상속받은 클래스는 본인의 일 외에도 다른 객체와 비교할 수 있다 라는 것을 알 수 있구. 
또 추상 클래스를 상속하면 클래스의 계층 구조가 생기는데 본인의 일 이외에 추가적인 기능을 할 수 있다 라고 알려주는 믹스인의 의미와 거리가 멀어서 계층구조가 생기지 않는 인터페이스가 믹스인에 적절하다고 볼 수 있는것 같아.
