### ISSUE TITLE
[아이템1] 정적 팩토리 메소드와 생성자 각각 사용하기 좋은 상황

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#6]

**Comment by csbsjy** [comment]
하나씩 들자면 동적으로 반환타입을 바꿔야 할 일이 있을 때 정적팩터리 메서드를 사용하기 좋을 것 같아. 싱글턴 클래스에도 유용하게 쓰이겠고. 생성자는 static 하지 않으니까 생성비용이 적게 들어서 굳이 클래스로더 초기화시점 때 생성해두지 않아도 되는 경우에 좋을것같아..! DI 프레임워크쓸때는 필수적이겠고 ..

**Comment by csbsjy** [comment]
+ 예제 구현
