### ISSUE TITLE
[아이템 20] 단순구현

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#60]
135p 골격구현의 작은변종 단순구현의 대표적인 예 SimpleEntry의 구현방식을 설명해주세여

**Comment by Gobukgol** [comment]
SimpleEntry의 경우 Map 인터페이스 내부에 있는 Entry 인터페이스를 간단하게 구현한 클래스야.
그래서 Entry 인터페이스에 정의된 기반 메소드들을 구현하고있어. 

SimpleEntry는 골격구현 처럼 인터페이스의 디폴트 메소드들을 제외한 기반 메소드들을 구현 하였지만 책에서 말한것 처럼 골격구현과 다르게 추상 클래스가 아니라 일반 클래스로 구현하였기 때문에 다른 골격 구현과는 다르게 그 자체로도 사용할 수 있다는 장점이 있어.

![image](https://user-images.githubusercontent.com/34976178/89609745-b5427b00-d8b3-11ea-90fc-07d03a2eba34.png)

일반 골격구현인 AbstractMap의 경우 추상 메소드인 entrySet() 메소드를 직접 구현하여 사용해야하는 반면, SimpleEntry의 경우 그 자체로 사용할 수 있는걸 볼 수 있어.
