### ISSUE TITLE
[아이템 24] 바깥클래스의 메모리를 해제못할 수 있다

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#65]
148p 첫번째 줄에 바깥클래스를 해제 못하는 경우에 대해서 알려줘

**Comment by pci2676** [comment]
예제는 못짰고..
정말 참조하고 있는지 확인 해봤어

```java
public class OuterReference {

    public class InnerClass {
        //바깥 클래스로 숨은 참조를 가진 상태
    }

    public static class StaticInnerClass {
        //바깥 클래스로 숨은 참조를 가지지 않는 상태
    }
}

```
위와 같은 코드를 작성하고 class 파일을 까보면 아래처럼 static 이 아닌 멤버 클래스는 this로 참조를 하고 있어
![image](https://user-images.githubusercontent.com/13347548/76148165-ffe28000-60e6-11ea-8ca0-8c72b271492d.png)

**Comment by pci2676** [comment]
예제코드와 visualVm으로 메모리 할당을 확인해 봤음!

아래와 같은 클래스를 만들어 두고 
먼저 `InnerClass`가 바깥 클래스인 `OuterReference`에 대한 참조를 가지고 있어서 
`OuterReference`가 GC되지 못하는 상황을 만들어 볼게!

```java
public class OuterReference {

    public class InnerClass {
        //바깥 클래스로 숨은 참조를 가진 상태
    }

}
```

아래와 같은 main 메서드를 작성했을 때

```java
public class Main {

    public static void main(String[] args) throws IOException {
        System.out.println("생성!");
        OuterReference.InnerClass innerClass = getInnerClass();
        System.out.println("메서드 내부에서 생성된 지역변수는 소멸예상!");
        
        System.in.read(); // 여기서 멈추자!
        innerClass.toString();
    }

    private static OuterReference.InnerClass getInnerClass() {
        OuterReference outerReference = new OuterReference();
        return outerReference.new InnerClass();
    }
    
}
```

main 메서드를 visualVm과 함께 실행시키고 
`System.in.read()`에서 스레드가 대기하고 있는 상황에서
GC를 강제로 실행시키면 우리는 현재 다른 곳에서 참조가 되어 살아있는 객체만을 볼수있지!
지금 main 메서드에서는 `InnerClass`를 반환하는 `getInnerClass()` 메서드 내부에
지역변수로 생성된 `OuterReference`가 메서드를 벗어나면서 GC의 대상이 되어야함을 예상 할 수 있지
하지만 실제로 GC를 실행후 메모리 할당 상태를 보면
![image](https://user-images.githubusercontent.com/13347548/76187238-2f44da00-6218-11ea-831a-91b673528fa2.png)
`OuterReference`의 메모리는 그대로 할당되어 있음을 확인할 수 있었어!

이제 `StaticClass`를 예제로 작성해보면 아래와 같이 `OuterReference`를 작성하고

```java
public class OuterReference {
    public static class StaticClass {
        //바깥 클래스로 숨은 참조를 가지지 않는 상태
    }
}
```

마찬 가지로 `StaticClass`를 가져오는 메서드를 만들어서 main 메서드를 작성하고

```java
public class Main {

    public static void main(String[] args) throws IOException {
        System.out.println("생성!");
        OuterReference.StaticClass staticClass = getStaticClass();
        System.out.println("메서드 내부에서 생성된 지역변수는 소멸예상!");

        System.in.read(); // 여기서 멈추자!
        staticClass.toString();
    }
    
    private static OuterReference.StaticClass getStaticClass(){
        return new OuterReference.StaticClass();
    }

}
```
 이전과 마찬가지로 visualVm으로 스레드가 멈춰있는 곳에서 
GC를 실행하고 메모리 할당 상태를 확인해보면
![image](https://user-images.githubusercontent.com/13347548/76189669-9feef500-621e-11ea-9e41-074961e21d8b.png)

`OuterReference`는 참조될 일이 없어서 메모리 할당이 되어있지 않아!
