### ISSUE TITLE
[아이템 21] synchronizedCollection

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#67]
> 137p. org.apache.commons.collections4.collection.SynchronizedCollection이다. ... java.util의 Collections.synchronized Collection 정적 팩터리 메서드가 반환하는 클래스와 비슷하다

이 두개가 뭐가 다른가여..?! 나는 org.apache.commons.collections4.collection.SynchronizedCollection 이거에만 synchronized 되나 했는데, readme에 쓴 예제 보니까 거기에도 synchronized 키워드가 있길래...!!

**Comment by pci2676** [comment]
이거 [리드미](https://github.com/Java-Bom/ReadingRecord/blob/master/%EC%9D%B4%ED%8E%99%ED%8B%B0%EB%B8%8C%20%EC%9E%90%EB%B0%94/effectiveJava/src/main/java/item21/README.md
)에 적어둔 그림을 같이 보면 좋은데!

아파치에서 만든 라이브러리는 버전 4.4가 되기 전까지 디폴트 메서드가 추가되었지만 구현이 되지않아서 Collection 객체와 잘 어우러진 게 아니라는 거를 말하는거 같아!

자바진영에서 만든 Collections 에서 만들어주는 synchronizedCollection은 디폴트 메서드가 추가될 때마다 잘 재구현 되서 나온거고!

둘 다 목적은 똑같은 구현체라고 보면될거같아!
