### ISSUE TITLE
[아이템 21] Predicate

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#68]
> 136p. 자바8의 Collection 인터페이스에 추가된 removeIf 메서드를 예로 생각해 보자. 이 메서드는 주어진 불리언 함수(predicate; 프레디키트)가 true를 반환하는 모든 원소를 제거한다.

Predicate를 처음 접해봐서 그런데, boolean, Boolean이랑 차이를 알려줄수 있나용

**Comment by pci2676** [comment]
`boolean`은 원시타입이고 `Boolean`은 참조타입!
`boolean`은 `true`/`false`,이고 `Boolean`은 `true`/`false`/`null`

`Predicate`는 우리 `stream`에서 `filter`내부에서 보던게 `Predicate`인데
`@Functional` 인터페이스이고 전달받은 매개변수를 `test()` 메서드를 호출해서 검사하지 
이때 `test()`에서 호출되는 메서드는 우리가 입력한 `boolean`을 반환하는 메서드!
