### ISSUE TITLE
[아이템 28] 제네릭타입과 가변인수메서드

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#69]
> p.166,  제네릭타입과 가변인수 메서드를 함께 쓰면 ~~

가변인수 메서드가 뭔가요 ? 그리고 어떤 경고가 발생하나요?

**Comment by chldbtjd2272** [comment]
`
 public static int sum(int... source) {
        int result = 0;
        for (int i : source) {
            result += i;
        }
        return result;
    }
`
가변인수 메서드는 가변적인 파라미터를 받을 수있는 메서드야 저렇게 선언하면 
VarArgsCalculator.sum(1,2,3)
VarArgsCalculator.sum(new int[]{1,2,3})
가변 파라미터를 받을 수 있어
