### ISSUE TITLE
[아이템8] finalizer를 사용한 클래는 finalizer 공격에 노출되어 심각한 보안 문제를 일으킬 수 있다.

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#7]
이부분 뭔소린지 모르겠다.
readObject랑 readResolve포함해서 설명 적어줘

**Comment by csbsjy** [comment]
역직렬화시  readObject 이라는 메서드가 실행돼. 만약 누군가 이 readObject 이라는 메서드가 Exception 을 던지도록 조작하면 gc 수행 시 finalizer가 실행 돼. 그 악의적인 목적을 가진 사람이 finalize를 오버라이딩하여 그 안에서 악의적인 로직을 담으면 심각한 보안 문제가 발생할 수 있어. 또, 이 finalize 메서드를 참조하는 정적필드를 만들면 사라지지도 않아. 
그래서 특정 클래스가 보안이 중요한 클래스라면 그 클래스를 상속받아 readObject, finalize 를 조작하여 악의적인 행위를 할 수 없도록 부모클래스에 finalize 메서드를 명시적으로 작성해두고 오버라이드되지 않도록 final 키워드를 쓰거나, final 클래스로 생성하라는 이야기같아. 정확하게 이해는 못했어, 백기선님 강의 들었는데 그분은 하위클래스 생성자에서 Exception 을 발생시키는걸 예로 드셨더라고. 그래서 비슷하게 직렬화-역직렬화 과정도 이해한건데 ㅈ ㅏ 신없습니다 ^^ ;

**Comment by csbsjy** [comment]
이 글이 해당 내용이랑 비슷한거같아서 공유할게 ~ 자식클래스 생성자에서 Exception 던지고 finalize 메서드에서 자신을 정적필드에 참조되도록 하는 예제야! https://yangbongsoo.gitbook.io/study/finalizer-attack

**Comment by csbsjy** [comment]
예제 올리기
