### ISSUE TITLE
[아이템 28] 핵심정리

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#70]
> p169, 배열은 런타임에는타입안전하지만 컴파일타임에는 그렇지않다.

배열이 공변타입이라 런타임 때 ArrayStoreException 난다고 하는내용 아니었나 ??? 왜 런타임 때 타입 안전하다는지모르겠어 ! 익셉션이 난다는게 안전하단 뜻인가 ,, 그냥 핵심정리가 이해가 안가여ㅛㅁ ..

**Comment by chldbtjd2272** [comment]
`
 public static int sum(int... source) {
        int result = 0;
        for (int i : source) {
            result += i;
        }
        return result;
    }
`
가변인수 메서드는 가변적인 파라미터를 받을 수있는 메서드야 저렇게 선언하면 
VarArgsCalculator.sum(1,2,3)
VarArgsCalculator.sum(new int[]{1,2,3})
가변 파라미터를 받을 수 있어
