### ISSUE TITLE
[아이템 26] 비한정적 와일드카드 타입

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#71]
> pg.158. Collection<?>에는 (null 외에는) 어떤 원소도 넣을 수 없다.

비한정적 와일드카드 타입 설명에서, Collection<?> 에는 어떤 원소도 넣을 수 없다고 설명하는데 비한정적 와일드카드 타입을 사용하면 원소 추가는 불가능하고 꺼내서 확인만 가능한거야?

**Comment by chldbtjd2272** [comment]
![스크린샷 2020-03-21 오전 2 38 04](https://user-images.githubusercontent.com/25260024/77190676-05938900-6b1d-11ea-894a-02402d880627.png)


맞아 확인만 가능하고 값을 넣을 수는 없어
