### ISSUE TITLE
[아이템 28] 실체화

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#72]
> pg.166 실체화되지 않아서 런타임에는 컴파일타임보다 타입 정보를 적게 가지는 타입이다.

위의 얘기를 보고 실체화는 컴파일 타임과 런 타임시의 타입 정보가 같은 타입을 의미하는것으로 생각했는데 맞게 이해한걸까??

**Comment by chldbtjd2272** [comment]
![스크린샷 2020-03-21 오전 2 20 02](https://user-images.githubusercontent.com/25260024/77189174-7d13e900-6b1a-11ea-8bf4-109af646c984.png)
[링크](https://docs.oracle.com/javase/tutorial/java/generics/nonReifiableVarargsType.html)

실체화 가능한 타입들은 명확하게 컴파일 타임때 뿐만 아니라 런타임때도 실체화 되어있는 애들이야
Object[] = new String[] 이런경우 컴파일,런타임때까지 타입이 유지되니 실체화타입이지

E,List<E>,List<String>같은 경우는 컴파일 단계에서만 타입체크를 하고 실제 런타임에 될때는 타입체킹이 풀려 우리가 따로 캐스팅을 안해도 값을 보장할 수 있도록해줘

위 링크를 보면 실체화 불가타입을 더 정확히 이해할 수 있어
