### ISSUE TITLE
[아이템 30] 한정적 와일드 카드를 사용하여 더 유연하게 계산

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#78]
> p.177 코드 30-2의 union 메서드는 집합 3개의 타입이 모두 같아야 한다.

근데 이거 와일드 카드 안쓰고 제네릭에서 그냥 전부 E써도 똑같이 한개로 강제할수 있는거아닌가?? 
그냥 `? extends String` 을 하라는건가..?
그럼 마찬가지로 `E extends String` 해도 되는거 아닌가???

**Comment by csbsjy** [comment]
한개로 강제하는 E를 사용한 메서드를 한정적 와일드타입을 사용해서 유연하게사용할 수 있다는 내용이얌!
E extends Number를 하면 Number의 하위클래스인 E 타입으로, 매개변수 2개와 반환타입을 고정시켜야하지만 ? extends Number를하면, 매개변수 1은 Integer, 2는 Long 등등이 가능해지겠징 ??

**Comment by pci2676** [comment]
뒤를 읽어보니까 `? extends E`하라는거 같기두 하고...

**Comment by csbsjy** [comment]
오호, 그러네 나는 ? extends Number 여기까지밖에 생각못했엌ㅋㅋ

```java
    public static <T> List<T> pci(List<? extends T> list1, List<? extends T> list2) {
        List<T> allList = new ArrayList<>();
        allList.addAll(list1);
        allList.addAll(list2);
        return allList;
    }
```
