### ISSUE TITLE
[아이템 7] 메모리 해제 대상이 무엇이 있는지

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#8]
가비지 콜렉터가 메모리 해제 대상을 무엇으로 판단하는지
(ex. 다 쓴 참조, 스코프 밖으로 밀어내는 것)

**Comment by csbsjy** [comment]
질문을 모르겠어 ! 메모리 해제 대상을 묻는거야, 아니면 그 대상을 찾는 과정을 묻는거야?

**Comment by csbsjy** [comment]
A 에서 생성된 B 인스턴스는 어떤 식으로 저장되며, 어떻게 GC 대상으로 판별되나요?

**Comment by chldbtjd2272** [comment]
stack영역은 누가 비워주나

**Comment by Gobukgol** [comment]
@csbsjy  A에서 생성된 B인스턴스는 힙 영역에 A가 B를 참조하는 방식으로 저장이 돼, 그래서  A에서 B로의 연결이 끊기거나 A자체의 연결이 끊긴다면 그 때 GC 대상이 돼.
@chldbtjd2272 Stack영역은 JVM이 관리해. Stack이라는 이름처럼 pop하고 push하는 방식으로 stack영역을 다뤄

**Comment by csbsjy** [comment]
https://javabom.tistory.com/7?category=835783
