### ISSUE TITLE
[아이템 30] extends Comparable

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#80]
> 코드 30-6 재귀적 타입한정을 이용해 상호 비교할 수 있음을 표현했다.

여기서 코드가 

``public static <E extends Comparable<E>> max(Collection<E> c)``
이렇게 나오는데 제네릭 문법에 빠삭하지 못해서,, ㅠㅠ 

Comparable은 interface 인데 extends로 되어있네?!

이 이유가 제네릭이 확장받는걸(?) 1개만 가능해서그런건지.. 왜 extends를 사용하는지 궁금해

**Comment by csbsjy** [comment]
구냥 제네릭 문법이래..! extends 와 super로만 구분하는,,,?
