### ISSUE TITLE
[아이템 33] 이종 컨테이너 패턴 로 타입

### ISSUE THREAD

**Issue by Gobukgol** [Java-Bom/ReadingRecord#83]
> pg.201 예컨데 HashSet의 로 타입을 사용하면 HashSet<Integer>에 String을 넣는 건 아주 쉬운 일이다.

이 부분이 조금 헷갈리는데 HashSet<Integer>을 로 타입으로 캐스팅하고 String add를 하면 String이 들어간다고 이해했는데 맞게 이해했나요??

**Comment by mjung1798** [comment]
이부분의 설명은 Favorites 클래스에서의 제약을 알려주고 있어
```java
public class Favorites {
    private Map<Class<?>, Object> favorites = new HashMap<>();

    public <T> void putFavorite(Class<T> type, T instance) {
        favorites.put(Objects.requireNonNull(type), instance);
    }

    public <T> T getFavorite(Class<T> type) {
        return type.cast(favorites.get(type));
    }
```
![image](https://user-images.githubusercontent.com/26458200/78493641-2cd89000-7784-11ea-84fd-aaf3e1e527a7.png)
만약 이런식을으로 put을 하게 되면, Integer type이라 했는데, String type이 나오게 되는거잖아. 그런데 Class row 타입으로 넣어서 put을 할 때는 문제가 일어나지 않아.
그런데 문제는 get을 할 때 Integer.class 임을 인식하고, get을 할 때 타입 캐스팅 과정에서 오류가 생겨서 다음과 같이 에러가 생기기 때문에 제약이 있다는걸 알려주고 있는 문맥이야!

즉 Key로 들어가는 인자를, 제네릭 타입과 같은 Class<Integer> 로 넘기지 않고, 로타입인 Class로 넘겼을 때 생기는 문제입니당

**Comment by mjung1798** [comment]
답변 잘못달아서 다시 넣었어~
![image](https://user-images.githubusercontent.com/26458200/79300711-7bbfbb80-7f22-11ea-86da-4a73f44b5ce8.png)

이것처럼 raw 타입으로 HashSet을 만들고 String을 넣으면 실제로 테스트가 통과해.

뿐만아니라 HashSet에서 contains(Object object) 를 넣어보면, 실제로 HashSet<Integer> 임에도 불구하고 String이 들어간걸 볼 수 있어!

* 추가로 contains(Object object) 에서 type 체킹은 그냥 IDE에서만 warning이 떠!
실제로 contains에 들어가는 인자가 제네릭으로 들어가있지 않아서, Integer인지, String인지 제네릭 타입체킹을 하지 않아!
