### ISSUE TITLE
[아이템 32] 실체화되는 제네릭케이스

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#84]
> p.191, 거의 모든 제네릭과 매개변수화 타입은 실체화되지 않는다. 

실체화가 런타임에도 살아있다는 것 같은데, 거의 모든이라고하면 실체화되는 경우도 있다는건가 ,,? 말이 어렵넹

**Comment by mjung1798** [comment]
제네릭 T / 매개변수화 타입 List<T> 는 실체화 되지 않는다....
엄,,, 롸,,,ㅎㅎ 실체화되는 경우는 잘 모르겠어요ㅠ

**Comment by mjung1798** [comment]
p166 : 소거 메커니즘 때문에 매개변수화 타입 가운데 실체화될 수 잇는 타입은, ``List<?>``와 ``Map<?,?>``와 같은 비한정적 와일드카드 타입뿐이다. 배열을 비한정적 와일드카드 타입으로 만들 수는 있지만 유용하게 쓰일일은 거의 없다.
