### ISSUE TITLE
[아이템 32] @SafeVarargs 

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#85]
> p.192, @SupressWarnings는 지루하고 가독성을 떨어뜨리고, 진짜 문제를 알려주는 경고를 숨긴다. 

@SupressWarnings 와 @SafeVarargs의 차이에 대해 예제작성해주세용.

**Comment by mjung1798** [comment]
@SafeVarargs
![image](https://user-images.githubusercontent.com/26458200/78498579-2519eb00-7786-11ea-964a-dfdb5d1af0b6.png)
@SuppressWarnings
![image](https://user-images.githubusercontent.com/26458200/78498628-6611ff80-7786-11ea-887c-158d1fd32940.png)
잠시만여,, 쓰는 중인데 잠깐만 저장

[참고]
https://www.baeldung.com/java-safevarargs
https://www.baeldung.com/java-suppresswarnings
