### ISSUE TITLE
[아이템 32] 배열이 클라이언트에게 노출되는 문제

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#86]
> p.191 가변인수 메서드를 호추라면 가변인수를 담기 위한 배열이 자동으로 하나 만들어진다. 그런데 내부로 감춰야 했을 이 배열을 그만 클라이언트에게 노출하는 문제가 생겼다.

배열을 노출한다는게 외부에서 접근이 된다는 건가?? 
어떤 상황을 말하는지 예시 보여주라

**Comment by pci2676** [comment]
엥 그냥 toArray 말하는건가

**Comment by mjung1798** [comment]
![image](https://user-images.githubusercontent.com/26458200/78500640-9f506c80-7792-11ea-8b19-5ea3ac5695bd.png)
넹 간단한 얘기인것 같아여 이렇게 배열로 내보내다 보니까, 아래 내용처럼 힙 오염과 관련한 내용이 발생하구,
저렇게 Local variable 로 만들었을 때 메세지 확인하면 Heap 오염을 경고하는 메세지가 필수적으로 떠!!

배열을 노출하여 문제가 발생했다 == 가변인수를 메서드를 선언한 클라이언트가 배열에 접근 할 수 있어 힙 오염의 문제가 나타날 수 있다.
