### ISSUE TITLE
[아이템 32] 다음 두 조건을 모두 만족하는 제네릭 vargs 메서드는 안전하다.

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#87]
> p.195 둘 중 하나라도 어겼다면 수정하라!
varargs 매개 변수에 아무것도 저장하지 않는다.

아무것도 저장하지 않는다는게 무슨 의미인지 모르겠어
메서드를 사용하려면 값을 넘겨야 하는데 이 경우에는 저장하지 않았다고 하는건가?
그러니까 아래와 같은 메서드가 있을때
`foo(T... args)` 사용하려면 `foo("a","b");` 이런식으로 사용하잖아?
이런경우 메소드 내 지역변수로 저장만 하지 않으면 된다는 뜻인가?

**Comment by mjung1798** [comment]
웅 메서드내 지역변수로 저장하지 말자는 의미 + 다시 덮어쓰지 말라는 의미로 보여
코드 32-1 예시를 보면 
![image](https://user-images.githubusercontent.com/26458200/78500886-0e7a9080-7794-11ea-86a8-0684ee00ad18.png)
stringList의 배열을 Object 배열에 넣었어. 이때도 힙오염으로 문제가 생길 뿐아니라

이 외에도  같이 연상이 되는게, 배열은 공변 타입이라는 점이었어
![image](https://user-images.githubusercontent.com/26458200/78501099-2f8fb100-7795-11ea-8af1-83e11e735037.png)
이건 내가 만든 예제인데, 오빠이전 질문이랑 뭔가 같은 맥락인거 같아!
클라이언트에 가변인수 배열을 노출해서 위와 같이, 다운 캐스팅시 허용되지 않는 저장도 가능해지는 거고
노출되서는 안되었던 가변인수 배열에, 허용되지 않는 작업으로 저렇게 다시 덮어쓰는 작업을 수행할 수 있는 부정확함 때문에 쓰지 말라고 하는 것 같아

즉, 메서드 안에서 사용할 때 가변인수 배열 값을 다시 할당하지 말라는 뜻 + 가변인수 배열을 다른 지역변수 인자에 (이상한 타입으로 저장할 수 있으니) 저장하지 말라는 뜻을 내포하는것 같아
