### ISSUE TITLE
[아이템 32] toArray

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#88]
193p 마지막 코드에서 toArray를 바로 String[]배열로 받는건 되는데 왜 pickTwo를 거쳐서 String[]로 받는건 안될까?

**Comment by mjung1798** [comment]
STUCK

**Comment by mjung1798** [comment]
이펙티브 자바의 pickTwo 예제에 대한 고찰 **p.193**

### 1. 제네릭 배열의 이중 타입추론

```java
static <T> T[] pickTwo(T a, T b, T c) {
  switch (ThreadLocalRandom.current().nextInt(3)) {
    case 0:
      return toArray(a, b);
    case 1:
      return toArray(b, c);
    case 2:
      return toArray(a, c);
  }
  throw new AssertionError();
}

static <T> T[] toArray(T... args) {
  return args;
}

public static void main(String[] args) {
  String[] strings = pickTwo("좋은", "빠른", "저렴한");  
}
```

다음 코드는 ClassCastException을 일으킨다.

```
Exception in thread "main" java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Ljava.lang.String; ([Ljava.lang.Object; and [Ljava.lang.String; are in module java.base of loader 'bootstrap')
	at Chap4_Generic.item32.PickTwo.main(PickTwo.java:58)
```

main 에서 pickTwo를 호출할때는 제네릭 변수 T가 String으로 타입 추론이 가능하다.

하지만 toArray의 제네릭 변수 T는  pickTwo의 타입이 제네릭 변수이므로 Object로 타입추론을 하게되고, ClassCasting Excetpion을 일으키게 된다.

즉, toArray의 반환값은 Object[] , pickTwo의 반환값은 String[] 이 되며, Object[]는 String[]의 하위타입이 아니기 때문에 이 형변환이 실패하게 된다.



### 2. 제네릭 리스트의 이중 타입추론 (java 11)

이펙티브 자바에 따르면 List를 적용한 경우에는 올바르게 프로그램이 돈다고 한다. 실제로 코드를 만들어보면

```java
static <T> List<T> pickTwoList(T a, T b, T c) {
  switch (ThreadLocalRandom.current().nextInt(3)) {
    case 0:
      return Arrays.asList(a, b);
    case 1:
      return Arrays.asList(b, c);
    case 2:
      return Arrays.asList(a, c);
  }
  throw new AssertionError();
}

List<String> strings = pickTwoList("좋은", "빠른", "저렴한");
```

이경우에는 컴파일이 성공한다.

Arrays.asList() 메서드 안을 그래서 살펴보았는데, 

<img width="520" alt="스크린샷 2020-04-15 오후 2 25 29" src="https://user-images.githubusercontent.com/26458200/79302886-841af500-7f28-11ea-8046-3ec53710082c.png">
<img width="713" alt="스크린샷 2020-04-15 오후 2 25 46" src="https://user-images.githubusercontent.com/26458200/79302888-87ae7c00-7f28-11ea-8384-b6793c212d87.png">

다음과 같이 asList에서도 위 코드를 호출한 pickTwoList의 T a, T b 변수가 제네릭이라 타입추론이 안되니, 이 안에들어가는 asList(T… a) 는 Object로 타입추론이 될 것이라 예상하였다.

하지만 이 코드에서는 Arrays.ArrayList(a); 가 ArrayList의 로타입을 리턴하며, List 로타입에서 List<String>으로 형변환이 올바르게 적용되어 pickTwoList의 결과를 제대로 리턴할 수 있다고 결론을 내렸다. 

<img width="610" alt="스크린샷 2020-04-15 오후 2 30 08" src="https://user-images.githubusercontent.com/26458200/79302968-a9a7fe80-7f28-11ea-87d3-2dd4445f3c34.png">


실제로 디버깅 결과도 T 배열이 Object로 타입추론 되서 들어감을 알 수 있었다. 하지만 여기서 Arrays.ArrayList(a); 를 거치면서 List<Object>가 아닌 List 로타입으로 리턴하였기 때문에 그 바깥에 있는 pickTwoList 에서 List<String>으로의 형변환이 올바르게 적용되었다는 가설이 성립한다.



### 3. 제네릭 리스트의 이중 타입 추론 (java 8)

하지만 똑같은 코드를 java8로 들어가서 Arrays.asList 를 찾아봤을 때

<img width="427" alt="스크린샷 2020-04-15 오후 2 32 52" src="https://user-images.githubusercontent.com/26458200/79302976-af054900-7f28-11ea-9d87-67c80a0ce853.png">


아래와 같이 새로운 ArrayList를 생성하는 부분에서, new ArrayList<T>(); 를 이용해서 생성함을 알게되었다. 다만 이렇게 될 경우에는 

위에서 제네릭이 추론했던대로 T는 Object로 들어가고, asList 에서 리턴하는 값은 List<Object>가 된다. 이렇게 List<Object>를 리턴하는 경우에는 List<String>으로 형변환이 되지 않을 텐데, 이 경우에도 위에서의 pickTwoList가 작동한다.

<img width="541" alt="스크린샷 2020-04-15 오후 2 35 08" src="https://user-images.githubusercontent.com/26458200/79302984-b62c5700-7f28-11ea-9c53-2e5535d04e36.png">


디버깅 결과도 T는 Object가 들어갔음을 알 수 있고, List<T>에는 List<Object>가 들어감을 알 수 있다.



### 4. 결론 및 의문

제네릭이 두번 중첩되게 되면, T는 타입추론을 Object로 하게된다. 하지만 이 경우에는 List<Object>를 List<String>으로 혹은 List<Integer>으로 타입 캐스팅을 해야하는 이슈가 생긴다. 

이때 자바는 어떻게 이 경우에 List<Object> -> List<String>으로 타입캐스팅을 해버린 것일까?

구글링을 이용해 <https://stackoverflow.com/questions/4581407/how-can-i-convert-arraylistobject-to-arrayliststring> 찾아보아도, converting 과정을 거쳐야하는 것으로 나온다.

**Comment by mjung1798** [comment]
### java8 vs java11

여기서의 List 로타입에 대한 가설은 성립하지 않는 것 같다.

java 8이 ``List<T>``로 return 타입이 선언되어있는 것 처럼,  java 11도 ``List<T>``로 return 타입이 선언되어있기 때문에, raw타입이라서 타입추론이 되었다는 가설은 기각된다.

**Comment by mjung1798** [comment]
### 결론

**item28 배열대신 리스트를 사용하라** 의 조언에 따른 런타임에 타입 정보 소거로 인해서 ``List<T>``의 타입추론이 되는 것으로 알 수 있다.

결국 핵심은

```java
public static<T> List<T> asList(T... a){
  return new ArrayList<>(a);
}
```

```java
public static<T> T[] toArray(T... args){
  return args;
}
```

이 두개에서 가변인수 배열이 인자로 들어왔을 때, return 타입을  List로 할 것이냐 Array로 할 것이냐에 따른 제네릭 타입추론이었다.

##### Array

Array의 경우에는 런타임에 제네릭 타입정보를 갖고있기 때문에, 위가설대로 T를 Object타입으로 캐스팅하며 Object[] -> String[] 으로 캐스팅 하는 과정에서 오류가 났었다 : ClassCastException

``Stringp[]) Object[]`` 과 같은 타입캐스팅이 없었기 때문에

#### List

리스트의 경우에는, 컴파일 타임에 캐스팅할 정보가 이미 결정이되고, 런타임때에는 제네릭의 소거라는 특성 때문에 캐스팅 에러가 나지 않는다.

정리하자면, 리스트 + 제네릭은 컴파일 타임에 결정된 캐스팅 정보가 올바르기 때문에 통과가 된다. 제네릭의 장점인 컴파일 타임에 타입이 안맞는 것을 체크해주는 걸 List에서도 수행하기 때문이다.

#### 결론

결국 제네릭의 타입 캐스팅을 런타임에 결정하느냐, 컴파일 타임에 결정하느냐가 관건 이었다. 

같은 맥락으로 만약 아래 코드가 있다고 했을 때도, 이 T 타입 자체는 컴파일 타임에 결정이 되기 때문에 마찬가지로 타입 캐스팅 에러가 나지 않는다.

```java
public static<T> T toArrayElement(T... args){
  return args[0];
}
```

> 위에서 제기했던 Object -> String 으로의 타입 캐스팅에 대한 관점은 전제가 잘못된 것이었다. 결국 제네릭 + List를 사용할 때는 컴파일 타임에 타입 검증이 끝난상태로 돌아간다는 것.

#### 추가 디버그 코드

실제로 T[] 로 인해 Object 배열로 받고 빼내는 코드가 컴파일러에서 컴파일 타임에 캐스팅 코드를 넣어주기 때문에 가능하다.

![image](https://user-images.githubusercontent.com/26458200/79538012-713a2900-80be-11ea-84e0-298028f5e84a.png)
![image](https://user-images.githubusercontent.com/26458200/79538015-7303ec80-80be-11ea-961c-a0fd6596eb00.png)
![image](https://user-images.githubusercontent.com/26458200/79538020-75fedd00-80be-11ea-8133-708a71ef3eae.png)
