### ISSUE TITLE
[아이템 34] 열거 타입 상수 맵 추가 시점

### ISSUE THREAD

**Issue by mjung1798** [Java-Bom/ReadingRecord#89]
> p.216 열거 타입 상수는 생성자에서 자신의 인스턴스를 맵에 추가할 수 없다. 이렇게 하려면 컴파일 오류가 나는데, 만약 이 방식이 허용되었다면 런타임에 NullPointerException이 발생했을 것이다. 열거 타입의 정적 필드 중 열거 타입의 생성자에서 접근할 수 있는 것은 상수 변수 뿐이다 (아이템 24)

왜왜?? 잘 모르겠어,, 아이템 24랑 왜 연관이 되어있는지도 어려움

**Comment by mjung1798** [comment]
그냥 그 당시에 다른 열거 타입들도 생성되었는지 아닌지 몰라서라는 걸까? (다른 상수타입들은 생성이 되었는지 안되었는지 모르니까)

근데 그러면 그냥 Map<String, Operation> = map.push 이런식으로 생성되면 map에 push! 이러면 안되나.,.?

아 애초에 map 필드자체가 초기화 안되었을 수 있겠구나

**Comment by Gobukgol** [comment]
음... 생성자에서 자신의 인스턴스를 맵에 추가할 수 없다는게 정적 필드의 경우 생성자에서 호출할 수 없도록 설계 되었더라구. 그 이유는 열거타입이 상수들을 먼저 생성하고난 다음 정적 필드를 초기화하기 때문이라고 생각해.
![image](https://user-images.githubusercontent.com/34976178/79310719-59846880-7f37-11ea-8e7a-63a997b44993.png)
그래서 컴파일 에러가 발생한다고 나와있고. 그래서 다른 메소드를 통해서 맵에 인스턴스를 put하려고 해봤는데 아래와 같이 NullPointerException이 발생했어.
```java
Operation(String symbol) {
        this.symbol = symbol;
        putString(symbol,this);
    }

    public void putString(String symbol, Operation operation) {
        stringToEnum.put(symbol,operation);
    }
```
![image](https://user-images.githubusercontent.com/34976178/79310912-a2d4b800-7f37-11ea-82fb-4f3aebd19350.png)
그러니까 생성자에서 정적 필드를 호출할 수 있게 허용한다면 NullPointerException이 발생할 것이라고 얘기하는걸로 생각했어!
그리고 아이템24를 언급한거에 대해선 같이 얘기해보고 싶어.. 나도 잘 이해를 못하겠어...

**Comment by mjung1798** [comment]
Enum에서의 생성 순서
1. Enum의 primitive type 상수 : ``static final int`` (Integer로 하면 안된다.)
2. Enum의 생성자
3. Enum의 static 변수 : ``static Map map;``

**Comment by mjung1798** [comment]
영판을 찾아보니 item 24참조가 item 34참조로 바뀌어 있었음.
![image](https://user-images.githubusercontent.com/26458200/79680444-a1163780-824a-11ea-9023-4a2d111d55d5.png)
