### ISSUE TITLE
[아이템7] 메모리 누수의 세번째 주범, 리스너 or 콜백

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#9]
예시를 보여주세여 (ex WeakHashMap)

**Comment by csbsjy** [comment]
마땅한 예시가 생각이 안나서 그냥 대충 클라이언트가 정의한 콜백을 넘겨받고 그대로 쿼리를 수행해주는 DriverManager 클래스로 짰엉 .. 
이런식으로 클라이언트가 정의한 콜백을 가지고 동작하는 클래스가 있다고 하면 이 클라이언트가 정의한 이 콜백은 한번쓰고 말지라도 이미 다른 인스턴스가 그 참조를 가지고 있기 때문에 메모리 누수의 근원이 될 수 있어. 그래서 명시적으로 더이상 쓸 일이 없다면 참조에 null 값을 주어서 gc 대상이 되도록 하거나 필드로 가지고 있지 말고 WeakHashSet의 key로 콜백을 넣어서 안쓰일 때 gc 대상이 되도록 해야해. 


![image](https://user-images.githubusercontent.com/47847993/72660039-83e38a00-3a0b-11ea-9b40-6dcbdcf4de72.png)
![image](https://user-images.githubusercontent.com/47847993/72660040-8ba32e80-3a0b-11ea-90e4-3bd34a292c8b.png)



WeakHashMap 으로 저장하는 방법. 
![image](https://user-images.githubusercontent.com/47847993/72660162-fef97000-3a0c-11ea-9ae8-5d12355edf81.png)

**Comment by pci2676** [comment]
```java
    @DisplayName("HashMap 테스트")
    @Test
    void test1() {
        //given
        Map<Foo, String> map = new HashMap<>();

        Foo key = new Foo();
        map.put(key, "1");

        //when
        key = null;
        System.gc();

        //then
        assertAll(
                "HashMap 은 참조를 끊어도 map 이 비어있지 않다.",
                () -> assertThat(map.isEmpty()).isFalse()
        );

    }

    @DisplayName("WeakHashMap 테스트")
    @Test
    void test2() {
        //given
        Map<Foo, String> map = new WeakHashMap<>();

        Foo key = new Foo();
        map.put(key, "1");

        //when
        key = null;
        System.gc();

        //then
        assertAll(
                "WeakHashMap 은 참조를 끊으면 map 이 비어있다.",
                () -> assertThat(map.isEmpty()).isTrue()
        );
    }
```
이렇게 해보니까 참조 수준에 따라 WeakHashMap은 GC가 우리가 생각한 대로 동작해주는거 같아
<img src="https://user-images.githubusercontent.com/13347548/72961948-380f5700-3df6-11ea-9489-1431cdd88d3f.png" alt="image" style="zoom:50%;" />
