### ISSUE TITLE
[아이템 34] 열거타입의 장점

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#90]
> p. 210. 열거타입은 Object 메서드를 높은 품질로 구현, Comparable, Serializable, 을 구현해놓았다.

위 내용에 대한 예제코드가 있으면 좋겠어유

**Comment by Gobukgol** [comment]
요게 맞는지 자신이 안나는데... 
열거 타입 상수들은 그 자체가 클래스이고 java.lang 패키지의 Enum 추상 클래스를 상속 받고있어. 그 Enum 추상 클래스는 Comparable, Serializable을 구현하고 있어.
![image](https://user-images.githubusercontent.com/34976178/79633206-0ad90780-819f-11ea-84cd-cef35c4fd996.png)

Comparable의 compareTo 메소드
![image](https://user-images.githubusercontent.com/34976178/79633244-38be4c00-819f-11ea-976d-35908e528351.png)

또 Object 클래스의 toString,equal,hashCode, clone 메소드를 구현하고 있고
![image](https://user-images.githubusercontent.com/34976178/79633177-dd8c5980-819e-11ea-9e47-e8e1d7c7f8ba.png)
