### ISSUE TITLE
[아이템 37] EnumMap 의 생성자가 받는 키 타입. 

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#91]
> p.228, EnumMap의 생성자가 받는 키 타입의 Class 객체는 한정적 타입 토큰으로, 런타임 제네릭 타입 정보를 제공한다.

런타임 제네릭 타입 정보를 제공한단 얘기가 무슨뜻이지?? 한국말이해를 못하겠엉 

```java
EnumMap<K extends Enum<K>, V> extends AbstractMap<K, V>
```

EnumMap의 Key 가 런타임에 Enum 타입이라는 것을 알게해준단뜻인가

**Comment by Gobukgol** [comment]
런타임시에 제네릭 타입정보가 소거 되니까 Key의 Class 객체를 전달해서 런타임에도 Map에 객체를 추가하거나 할때 타입 정보를 알기위해서로 이해했어!
[https://stackoverflow.com/questions/3459259/why-enummap-constructor-needs-class-argument](url)
여기에서도 같은 얘기를 하고있는데 한번 보는것도 좋을것 같아.
