### ISSUE TITLE
[아이템 37] 점층적 팩터리

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#92]
> p.230, 두번째 수집기인 병합함수인 ~ 점층적 팩터리를 제공하기 때문이다.

이넘얘기랑은 먼거같아서 혼자 해결해보려고했는데 코드 자체가 많이 으려워서 이쪽이 잘 안읽형 ㅠㅠ 
코드 + 해당문단이랑 같이 설명하면서 어떻게 Map으로 반환하는건지 알랴주세요 ..

**Comment by Gobukgol** [comment]
일단 groupingBy하고 toMap의 차이가 groupingBy는 하나의 key에 여러개의 value, 
toMap은 하나의 key에 하나의 value의 맵을 반환하는데, key와 value가 일대일 대응이기 때문에 같은 key값이 나왔을때 어떻게 처리할지 명시를 해줘야해. 그게 문단에서 말하는 병합 함수 (x,y) -> y 인 것이고, 얘는 같은 key일 때 새로운 값으로 갱신하겠다는 의미야. 

그럼 코드를 한번 보면
```java
transitionMap = Stream.of(values()).collect(Collectors.groupingBy())
```
는 전이 열거 타입의 상수들을 일대다 대응의 Map으로 만들려고 하는데
```java
groupingBy(t -> t.from,  () -> new EnumMap<>(Phase.class),Collectors.toMap())
```
그 맵을 EnumMap으로 구성하려는데 맵의 Key를 전이(t)에서 이전 상태(t.from)로 묶고, 
대응되는 value인 전이(t)들을 다시한번 Map으로 구성하겠다. 여기까지가 책에서 **"이전 상태에서 ~에 대응하는 맵"**  부분이야.

그럼 이제 toMap을 봐야겠지?
```java
toMap(t -> t.to, t -> t, (x,y) -> y, () -> new EnumMap<>(Phase.class))
```
Map을 만들껀데 맵의 Key를 전이(t)에서 이후 상태(t.to)로 묶고, 대응되는 value를 전이(t)로 할꺼야. 그런데 만약 Key인 이후 상태가 같으면 기존 value를 사용하지 않고 새로운 value로 갱신할꺼야. 그리고 만들 맵을 EnumMap으로 구성한다. 라는 의미가되는거지.

그래서 전이 맵은 이전 상태를 Key로 하는 맵인데 그 맵의 value는 이후 상태를 Key로 하고 전이를 value로 가지고 있는 Map이다. 가 되는거야.
그렇게 만든 Map은 다음과 같은 결과를 가지고있어.
![image](https://user-images.githubusercontent.com/34976178/79633098-3d363500-819e-11ea-81ba-2deb7c6ef432.png)

내가 이해한건 이정도인데 도움이 됬으면 좋겠네...ㅜ

**Comment by csbsjy** [comment]
(x,y) -> y 
는 Stream 을 돌리는 클래스를 병합하는 것임
