### ISSUE TITLE
[아이템 37] EnumMap의 성능 공간적 이점

### ISSUE THREAD

**Issue by chldbtjd2272** [Java-Bom/ReadingRecord#94]
> p 228 두번째 문단

enumMap을 쓰지 않았을때 성능, 공간적 인점을 못얻는다 했는데 어떤 차이가 있을까

**Comment by Gobukgol** [comment]
Collectors의 groupingBy 메소드에 따로 사용할 Map 구현체를 명시하지않으면 디폴트로 HashMap을 사용하게 되있어서 이 경우에 EnumMap과 HashMap의 차이점이라고 볼 수 있을 것 같아. 

공간상의 이점으로는 HashMap의 경우 Value에 대해 Node를 사용하고 있고, EnumMap의 경우 배열을 사용하고 있어서 EnumMap이 공간상 이점이 존재하고

성능은 HashMap은 인덱스를 hash로 사용하니까 key값을 hashing 하는 과정이 추가로 들어가지만 EnumMap은 열거 상수의 ordinal 값을 인덱스로 사용하니까 EnumMap의 성능상 이점을 얘기할 수 있을것 같아.
