### ISSUE TITLE
[아이템 38] 특정 연산에서 사용 할 수 없는 EnumSet, EnumMap 예시

### ISSUE THREAD

**Issue by pci2676** [Java-Bom/ReadingRecord#96]
> p.235 특정 연산에서는 EnumSet과 EnumMap을 사용하지 못한다.

이거 어떤 경우인지 예시 점!

**Comment by Gobukgol** [comment]
해당 문맥의 코드인 BasicOperation 과 ExtendedOperation은 둘다 Operation을 구현하고 있지만, 사실상 둘은 서로 다른 열거 타입이기 때문에 같은 열거 타입만 허용하는 EnumSet과 EnumMap은 BasicOperation과 ExtendedOperation을 동시에 담을 수 없어.
![image](https://user-images.githubusercontent.com/34976178/79717393-7bedfb80-8314-11ea-8add-250ae16ddc72.png)
