### ISSUE TITLE
[아이템 39] @interface 의 value 메서드

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#98]
> p. 241, 

```java
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface ExceptionTest {
    Class<? extends Throwable> value();
}
```
이렇게 작성하며면

![image](https://user-images.githubusercontent.com/47847993/80050547-e25f5d80-8550-11ea-94bb-14cec3b15b38.png)

이렇게 애노테이션의 매개변수 타입이 되더라고

신기하당. value() 가 애너테이션 타입을 사용할 때 매개변수를 정의하는 약속인건가? 
value() 말고 또 다른게 있나? 

매개변수를 여러개 받을 수는 있나? 대충 뒷부분보니까 배열이나, 중복해서 사용할 수는 있는거같은데 .. 매개변수는 클래스타입만 가능한가?

**Comment by pci2676** [comment]
>신기하당. value() 가 애너테이션 타입을 사용할 때 매개변수를 정의하는 약속인건가?

[오라클 자바 8 어노테이션 스펙](https://docs.oracle.com/javase/8/docs/technotes/guides/language/annotations.html)에서 찾아 보면 
>In annotations with a single element, the element should be named value  

라고 나와 있듯 단일 요소를 가지면 `value`라고 네이밍을 해야한데

>value() 말고 또 다른게 있나?

`value`처럼 지정된 건 없지만 우리가 따로 생성할 수는 있고!

>매개변수를 여러개 받을 수는 있나? 대충 뒷부분보니까 배열이나, 중복해서 사용할 수는 있는거같은데 .. 매개변수는 클래스타입만 가능한가?

마찬 가지로 스펙에 나와 있는데
>Return types are restricted to primitives, String, Class, enums, annotations, and arrays of the preceding types.

원시타입, 스트링, 클래스, 이넘, 어노테이션을 허용하고 이러한 타입들의 배열까지 허용하고 있어!
