### ISSUE TITLE
[아이템 39] 해당 예외의 클래스파일이 런타임에는 존재하지 않을 수 있다

### ISSUE THREAD

**Issue by csbsjy** [Java-Bom/ReadingRecord#99]
> p. 242, 단 해당 예외의 클래스파일이 컴파일타임에는 존재했으나 ~

해당 예외의 클래스파일이 이 예제에서 ArithmeticException 클래스를 말하는건가? 컴파일 타임에는 존재하고 런타임에는 존재하지 않을 수 있나?  TypeNotPresentException 을 던지는 상황을 보여주쎄요

**Comment by pci2676** [comment]
확실하지 않은데 java 와 javac 가 서로 다른 클래스 패스 옵션을 들고 있으면 가능할 것 같아
